### ISSUE TITLE
Make number format configurable

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/VueDatatable#1]
At the moment decimal numbers in Datatables are rendered with . as decimal sep. and , as thousands sep. - It would be nice if we can configure this.

Maybe a fix in combination with:
https://github.com/laravel-enso/Core/issues/26

**Comment by aocneanu** [comment]
I believe that right now only the totals are formatted by the table component. Also, only `,` is added by the numberFormat function.

I can add a section for customising the separator in the `config/datatable.php` file.

We want to keep the package independent from Enso.

We also have the global numberFormat filter in Enso, so maybe we should address that also. Regarding laravel-enso/Core#26 I don't see a real benefit for user customisable formats. Maybe a section in the config where we can set formats for every locale.

@gandesc , what do you think?

**Comment by mauthi** [comment]
Additional thought: Maybe you should separate "displayFormat" and "exportFormat"

**Comment by aocneanu** [comment]
My team and me are looking for a nice JS lib to handle number formats for both  data tables and the main project.

Until now we found http://openexchangerates.github.io/accounting.js, it looks promising.

If you have alternatives write them here.

**Comment by mauthi** [comment]
looks good for frontend, but I think we need something for backend too (e.g. exporting to excel)

**Comment by aocneanu** [comment]
@gandesc please update docs.

**Comment by mauthi** [comment]
The BE part is still open (number format for excel export). Should I create a new issue for this?

**Comment by aocneanu** [comment]
We're not interested (on our part) in exporting more than just plain xls files. The improvements for xls I have in mind have only to do with scalability.

**Comment by mauthi** [comment]
ok, the problem is that it’s not possible to use the excel files because decimal separtor is wrong - so the values get dates because of „.“ instead of „,“ and it’s not possible to change this (in an easy, daily usable way)

**Comment by aocneanu** [comment]
>ok, the problem is that it’s not possible to use the excel files because decimal separtor is wrong - so the values get dates because of „.“ instead of „,“ and it’s not possible to change this (in an easy, daily usable way)

I not sure what you mean.. the package does not transform in any way the values from the database. So if you have an int value of `1232131 ` this is exactly what the xls field will contain, under a General format

This is an export I just did:, check the `order` column:

![image](https://user-images.githubusercontent.com/16073274/38074056-1fbf47f4-3336-11e8-8dd2-9dda14c789f5.png)

**Comment by mauthi** [comment]
for int values its ok - but decimal values are stored with dot in database.

E.g. 
- Database: 12.03
- Export: 12.03
- Excel changes Value to 12.03.2018 (because it parses value as date and expects decimal values with comma)
- So what I’m needing is export.decimal_separator = ‚,'

**Comment by mauthi** [comment]
can we reopen that because it's not closed in my eyes?

**Comment by aocneanu** [comment]
@mauthi try in tinker `Model::first()` where `Model` is the base model for the problematic table. And then drop here a print screen with the result.

**Comment by mauthi** [comment]
The model isn't the problem - in the model the number is `12.03` (which is correct) - but in the export the number should be transformed to `12,03` (comma as decimal separator like in Germany used)

**Comment by aocneanu** [comment]
I insist :)
