### ISSUE TITLE
Add ability to toggle controls visibility

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/VueDatatable#103]
This is  a **feature request**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

Support toggling the (left-side) controls of a datatable

Example implementation:
add the following structure to the json (root level)
```json
"controls": {
        "length": true,
        "columns": false,
        "style": false,
        "reload": true,
        "reset": false
    },
```
expose (in datatable config):
```php
    'controls' => [
        'length' => true,
        'columns' => true,
        'style' => true,
        'reload' => true,
        'reset' => true
    ],
```
the following structure would result in the following required change in `TopControls.vue`
```Vue
                <length-menu :template="template"
                    :length="length"
                    v-on="$listeners"
                    v-if="template.controls.length"/>
                <column-visibility
                    :template="template"
                    :i18n="i18n"
                    v-on="$listeners"
                    v-if="template.controls.columns"/>
                <style-selector
                    :template="template"
                    class="is-hidden-mobile"
                    v-if="template.controls.style"/>
                <button class="button"
                    @click="$emit('reload')"
                    v-if="template.controls.reload">
                    <span class="icon is-small">
                        <fa icon="sync"/>
                    </span>
                </button>
                <button class="button"
                    @click="$emit('reset')"
                    v-if="template.controls.reset">
                    <span class="icon is-small">
                        <fa icon="undo"/>
                    </span>
                </button>
```
(and accept `controls` in `src/app/Classes/Attributes/Structure.php`)

### Expected behaviour

The attribute should be optional, and default to displaying all controls.

When defined; in the suggested format above each key should ideally still be optional

Alternative implementation:
Alternatively, an array of to-disable (or enabled?) elements should be passed; similar to how `actions` are defined in FormBuilder.

**Comment by aocneanu** [comment]
I'm not convinced about this.

Why wouldn't you want in a table, for instance, the `reload` button ?

**Comment by jlsjonas** [comment]
The reload button is the only one we've kept actually (along with visible rows) on the left side

As to why... simplicity: column visibility, row styling, ... are _cool_ features; but clutter the interface.
`reset`... very useful during development, but pretty useless in a production environment (and confusing towards _regular_ users)

**Comment by aocneanu** [comment]
@jlsjonas , do you have time for  PR on this?

I can specify all the details needed.

**Comment by jlsjonas** [comment]
I can look into it _soon_

**Comment by jlsjonas** [comment]
>I can specify all the details needed.

Waiting on these to be sure, unless you confirm the suggestion in OP is good

**Comment by aocneanu** [comment]
will provide it in the next days.

**Comment by aocneanu** [comment]
lets change

```json
"controls": {
        "length": true,
        "columns": false,
        "style": false,
        "reload": true,
        "reset": false
    },
```
with 
```
"controls": {
        "length": true,
        "columns": false,
        "style": false,
        "reload": true,
        "reset": false
    },
```

**Comment by aocneanu** [comment]
lets change:

```json
"controls": {
        "length": true,
        "columns": false,
        "style": false,
        "reload": true,
        "reset": false
    },
```
with 
```json
"controls": [ "length", "columns", "style", "reload", "reset" ],
```

and

```js
v-if="template.controls.length"/>
```

with

```js
v-if="template.controls.includes('length')"/>
```

`controls` should be added in the main config file and added to the templates by the builder, if the setting is not overridden in the local template.

**Comment by aocneanu** [comment]
Merged
