### ISSUE TITLE
Unknown Attribute(s) Found: "readSuffix"

### ISSUE THREAD

**Issue by shusharin** [laravel-enso/VueDatatable#104]
This is  a **bug**.

### Prerequisites
* [ x ] Are you running the latest version?
* [ x ] Are you reporting to the correct repository?
* [ x ] Did you check the documentation?
* [ x ] Did you perform a cursory search?

### Description

Hi! I did just composer update.
All pages with tables was crushed. 
Request init return: "Unknown Attribute(s) Found: "readSuffix"".
Attribute readSuffix - exists in docs: https://docs.laravel-enso.com/packages/vue-datatable.html#template

composer.json require section:
```
"require": {
        "php": "^7.1.3",
        "fguillot/json-rpc": "^1.2",
        "fideloper/proxy": "^4.0",
        "laravel-enso/vuedatatable": "^1.7",
        "laravel/framework": "5.7.*",
        "laravel/tinker": "^1.0",
        "maatwebsite/excel": "^3.0",
        "phpoffice/phpspreadsheet": "^1.5",
        "swiftmailer/swiftmailer": "6.0"
    }
```
template json without buttons & columns:

```
{
    "routePrefix": "calls",
    "readSuffix": "data",
    "crtNo": false,
    "selectable": true,
    "buttons": [],
    "columns": []
}
```

**Comment by aocneanu** [comment]
In 2.13.0 this param was deprecated. Please read the full changelog since then.

I updated the docs just now.

**Comment by shusharin** [comment]
2.13.0

**readSuffix** was renamed to dataRouteSuffix and it's now optional, being defined globally in the datatables.php config file, with a default value of tableData. If needed, you may overwrite it per each table template
