### ISSUE TITLE
Allow Row buttons to have a label

### ISSUE THREAD

**Issue by jammy-git** [laravel-enso/VueDatatable#107]
This is  a feature request.

### Description
It seems at the moment the row buttons will only display an icon. I believe it would be useful to be able to define a label for these buttons instead of, or including an icon.

**Comment by aocneanu** [comment]
This is how the table was 1.5 years ago, in the non spa version (the datatable package). We got to the conclusion that having “show” displayed 10 times on each table page was not really beneficial...

Don’t you think?

**Comment by jammy-git** [comment]
Personally I think that's a decision that should be left to the developer/designer?

If you want your plugin/framework to be widely adopted then it needs to be flexible in order to suit many different situations.

What does someone do if there is an action for which an icon isn't obvious at describing it?

**Comment by aocneanu** [comment]
We now have the options to add tooltips too for row buttons.
