### ISSUE TITLE
Undefined property: stdClass::$nullLast

### ISSUE THREAD

**Issue by shusharin** [laravel-enso/VueDatatable#108]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

Crash sorting - 
```
exception: "ErrorException"
file: "..../vendor/laravel-enso/vuedatatable/src/app/Classes/Table/Builder.php"
line: 141
message: "Undefined property: stdClass::$nullLast"
```
In doc: https://docs.laravel-enso.com/packages/vue-datatable.html#template

> nullLast, optional, makes the sorting on this column sort all null values last

### Steps to Reproduce
1. Use only laravel-enso/VueDatatable without Enso
2. Just updated to last version 
- Enso core with all enso packages (+migrations) included - why? No need it. 
3. All sorting was broken.

Example template:

```
{
    "routePrefix": "calls",
    "dataRouteSuffix": "data",
    "crtNo": false,
    "selectable": true,
    "buttons": [     ],
    "columns": [
        
        {
            "label": "ID",
            "name": "id",
            "data": "calls.id",
            "meta": [
                "searchable",
                "sortable"
            ]
        }
        , {
            "label": "Status",
            "name": "status",
            "data": "calls.status",
            "meta": [
                "sortable",
                "slot"
            ]
        }
        , {
            "label": "Date / time",
            "name": "start_time",
            "data": "start_time",
            "meta": [
                "slot",
                "sortable"
            ]
        }
   ]
}
```

**Comment by aocneanu** [comment]
could you please log the request in you table builder class and post it here?

It should contain "nullLast" for each column.

Did you recently upgraded to a new version? If so, don't forget to "reset" the table from the interface, because you probably have the last state saved in the localStorage.

**Comment by shusharin** [comment]
Request::
```
Obj {#801
  +"columns": array:14 [
    0 => "{"name":"id","data":"calls.id","meta":{"searchable":true,"sortable":true,"sort":null,"total":false,"date":false}}"
    1 => "{"name":"status","data":"calls.status","meta":{"searchable":false,"sortable":true,"sort":null,"total":false,"date":false}}"
    2 => "{"name":"start_time","data":"start_time","meta":{"searchable":false,"sortable":true,"sort":"ASC","total":false,"date":false}}"
    3 => "{"name":"contact_phone_number","data":"contact_phone_number","meta":{"searchable":true,"sortable":true,"sort":null,"total":false,"date":false}}"
    4 => "{"name":"login","data":"login","meta":{"searchable":true,"sortable":true,"sort":null,"total":false,"date":false}}"
    5 => "{"name":"offer_name","data":"offers.name","meta":{"searchable":true,"sortable":true,"sort":null,"total":false,"date":false}}"
    6 => "{"name":"campaign_name","data":"campaign_name","meta":{"searchable":true,"sortable":true,"sort":null,"total":false,"date":false}}"
    7 => "{"name":"tags","data":"tags","meta":{"searchable":false,"sortable":false,"sort":null,"total":false,"date":false}}"
    8 => "{"name":"cpn_region_name","data":"cpn_region_name","meta":{"searchable":false,"sortable":true,"sort":null,"total":false,"date":false}}"
    9 => "{"name":"communication_number","data":"communication_number","meta":{"searchable":false,"sortable":true,"sort":null,"total":false,"date":false}}"
    10 => "{"name":"price","data":"price","meta":{"searchable":false,"sortable":true,"sort":null,"total":true,"date":false}}"
    11 => "{"name":"price_internal","data":"price_internal","meta":{"searchable":false,"sortable":true,"sort":null,"total":true,"date":false}}"
    12 => "{"name":"last_call_record","data":"last_call_record","meta":{"searchable":false,"sortable":true,"sort":null,"total":false,"date":false}}"
    13 => "{"name":"wait_duration","data":"wait_duration","meta":{"searchable":false,"sortable":true,"sort":null,"total":false,"date":false}}"
  ]
  +"meta": "{"start":0,"length":10,"sort":true,"total":true,"enum":false,"date":false,"actions":false,"forceInfo":false}"
  +"search": null
  +"filters": "{"calls":{"status":null,"offer_id":[],"webmaster_id":[]},"calls_tags":{"tag_id":[]}}"
  +"intervals": "{"calls":{"date_at":{"min":null,"max":null,"dbDateFormat":"Y-m-d","format":"d.m.Y","locale":"ru","time":true,"minLabel":"От","maxLabel":"До"}}}"
}
```
"nullLast" is missing.
Was clear LS manually  in Chrome.

Upgraded by composer.

**Comment by aocneanu** [comment]
what's "clear LS manually in Chrome"

**Comment by aocneanu** [comment]
aah, local storage:D

you just need to press the reset button on the table 
![image](https://user-images.githubusercontent.com/16073274/49225963-05ceb900-f3ee-11e8-81b8-f02393df4182.png)

**Comment by shusharin** [comment]
yeah, i know about this button, thx )))
Clear manually for more transparency

**Comment by aocneanu** [comment]
Take a look in chrome's console under the vue tab and inspect the a column from the template. Is `nullLast` present?

![image](https://user-images.githubusercontent.com/16073274/49226868-6a8b1300-f3f0-11e8-9c3f-81e093c45b55.png)

**Comment by shusharin** [comment]
![image](https://user-images.githubusercontent.com/5540885/49227184-8e068b80-f3f9-11e8-9ec3-22c81bced3be.png)

**Comment by aocneanu** [comment]
so here you have it.

Are you really sure that you pressed the reset button from the table?

**Comment by shusharin** [comment]
yeah 100% and tried clear LS manually

**Comment by shusharin** [comment]
only fix like in pull request help me

**Comment by aocneanu** [comment]
I'm really trying to help you. What you did in the pull request "fixes" your problem but breaks the functionality.

Please tell me if in your `VueTable.vue` file [this line](https://github.com/laravel-enso/VueDatatable/blob/master/src/resources/js/components/enso/vuedatatable/VueTable.vue#L377) is present.

Did you compile after upgrading?

Did you cleared the cache maybe (I'm not aware of how you're compiling)

**Comment by aocneanu** [comment]
This file does not reside in the vuecomponents package, but in vuedatatable.
Apparently you have the BE upgraded but not the FE and that's strange..

**Comment by shusharin** [comment]
upgrade /resources/js/components/enso/vuedatatable - helped
Thx!

not use php artisan vendor:publish --tag=enso-assets
because it's copy much extra
