### ISSUE TITLE
Case insensitive search in Postgresql

### ISSUE THREAD

**Issue by shusharin** [laravel-enso/VueDatatable#110]
This is  a **feature request**.

### Prerequisites
* [ x ] Are you running the latest version?
* [ x ] Are you reporting to the correct repository?
* [ x ] Did you check the documentation?
* [ x ] Did you perform a cursory search?

### Description

In Postgresql LIKE work only case sensitive.
Do you have any idea, where we can define search operator ILIKE. 
Maybe in template.json like this:
```
.....
,{
            "label": "Offer",
            "name": "offer_name",
            "data": "offers.name",
            "searchOperator": "ILIKE",
            "meta": [
                "searchable",
                "sortable",
                "slot"
            ]
        }
```
**searchOperator** default always  = LIKE

This [row](https://github.com/laravel-enso/VueDatatable/blob/master/src/app/Classes/Table/Filters.php#L38) will changed:

`$query->orWhere($column->data, $column->searchOperator, '%'.$arg.'%');`

### Expected behavior

Case insensitive search

### Actual behavior

Case sensitive search in Postgresql

**Comment by aocneanu** [comment]
Would you ever want something else but "ILIKE" for PostgreSQL ?

If not it would make more sense to add an option at the global config level...

**Comment by shusharin** [comment]
I think, it will be only ILIKE.

Not sure about global config level. Sometimes, we have two or more type of database in one project (MySQL + PostgreSQL etc).

More correct - used table template configuration or column configuration. Because some pages get data from PostgreSQL, and other pages get data from MySQL.

**Comment by aocneanu** [comment]
The way I see it a global option with the ability to overwrite it in templates seems the way to go.

Why would you need it at a column level?

**Comment by shusharin** [comment]
Sorry for my long response.

Yeah, you right! Column level it was  too much.
We can't join from other database in Eloquent query (when we talk about different type of databases).

Totally - need two levels: 
- global from config.
- templates level.

I can try prepare pull request for this feature on this weekend.
