### ISSUE TITLE
Allow searching for/filter by enum (+translated) string

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/VueDatatable#121]
This is  a **feature request**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

Allow searching for an enum value

### Expected behavior

When searching for something visible for a user (i.e. the enum value tied to the numerical stored data), returning matching items

### Actual behavior

Enum value is not taken into account during search, only it's numerical value

**Comment by aocneanu** [comment]
Search by key, instead:

`MyEnum::get(MyEnum::Constant`)

This way you get around translations also.

**Comment by jlsjonas** [comment]
🤔 I'm not sure how that would fit in with the VueDatatable query.

To clarify, I'm _expecting_ that if I search in the DT search field that I can find results based on the displayed text (specifically for enums) and not it's stored number in the database, as this is information that the user would not know nor have.
![image](https://user-images.githubusercontent.com/932193/51824136-c1727300-22e1-11e9-9962-32a5839a5490.png)

Specific example, for https://www.laravel-enso.com/administration/people/ I would expect the following search to include all entries with Title being "Ms" (if that is set as a searchable field)
![image](https://user-images.githubusercontent.com/932193/51824230-05657800-22e2-11e9-82ad-e02a3509724d.png)

**Comment by aocneanu** [comment]
Oh, that wouldn't work anyway, the table searches in database columns not in enums.

For this situation add a vue-select-filter with the values from the enum. Check https://laravel-enso.com/examples/table, SeniorityEnum. You have there all the needed resources.
