### ISSUE TITLE
Clickable not working if column is hidden because of responsive (row in event payload is undefined)

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/VueDatatable#122]
This is  a bug.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
If a column is hidden (and visible by clicking on + button) the clickable meta is not working.
The row param in event payload is undefined

### Steps to Reproduce
1. Create a table with at least one column hidden
2. Add "clickable" to this column meta
3. Try to click on this column and inspect event payload in vue devtools

### Expected behavior
Row should contain info of row

### Actual behavior
Row is undefined

**Comment by aocneanu** [comment]
Only a few hours since your comeback and you are already finding all the hidden bugs :)))

**Comment by aocneanu** [comment]
The frontend needs a pretty big refactor, I'll do it once I will have the time.

The refactor will cover the problem you raised here.

Until then we will leave this open.

**Comment by aocneanu** [comment]
Fixed in last version.
