### ISSUE TITLE
custom_total

### ISSUE THREAD

**Issue by MonteiroCM** [laravel-enso/VueDatatable#124]
This is  a **bug | feature request**.

### Prerequisites
* [ x] Are you running the latest version?
* [ x] Are you reporting to the correct repository?
* [x ] Did you check the documentation?
* [x ] Did you perform a cursory search?

### Description

I would like to total a column. but I get string "valor custom total", and i like value change for each page. when i use total get all . in the image should give -798 but I get 177,337.28

//Table Templates I put

{
        "label": "Valor",
        "name": "valor",
        "data": "lancamentos.valor",
        "meta": [
            "searchable",
            "sortable",
            "customTotal"
        ],
        "money": {}
    }

### Expected behavior

I expected command meta["total"] give me the sum of data show on screen but it get all . I try to user meta["customTotal"] but show me the string 
### Actual behavior

USE meta["customTotal"]
![totalsoma](https://user-images.githubusercontent.com/2496628/52180688-92bc3700-27d0-11e9-9efb-4c93c346c837.png)
USE meta["total"]
![somatorio_total](https://user-images.githubusercontent.com/2496628/52180988-c3ea3680-27d3-11e9-9f48-90638e747e63.png)

but expect to total is (-798)

**Comment by aocneanu** [comment]
1. You don't need `customTotal`. It's meant for more complex situations where you have more than one column with totals and you want to do operations between the totals

2. The `total` option displays the total of the whole selection (67 pages in your situation), of course.

If you start filtering you will see that the total will adapt.

**Comment by MonteiroCM** [comment]
Yes , I know that but,
I would like the total shown on the first page to be only from the first page, and when i change to 2 page will be the total of 2 page, and so forth..

**Comment by aocneanu** [comment]
Sorry, this package is not able to do that.

**Comment by MonteiroCM** [comment]
So I thought about using, customTotal but i cant to that.. this is rsolve ?
ok so i will think another way to make this...
