### ISSUE TITLE
How i can get primary (unique) id for custom action [Help]

### ISSUE THREAD

**Issue by alanwhite2019** [laravel-enso/VueDatatable#127]
************ Help Needed ****************

Hi guys.
I am newbie with VueJS and VueDatatable, i am looking for some guidance. I have integrated this datatable in my application but seems to be stuck in custom action where i have to extract a unique record based on the primary key and populate that record on a modal.
**What I have done right now:**
1. I have placed a new 'Details' button that opens a new modal on click event.
![image](https://user-images.githubusercontent.com/47517461/52550229-f5c55380-2df8-11e9-9c30-126eea0af90c.png)
2. I also added a new slot type column of primary ID in .json table.
![image](https://user-images.githubusercontent.com/47517461/52550266-2a390f80-2df9-11e9-81fe-4e71ec1c193b.png)

**Problem facing:**
1. I am unable to get that "ID" in my .vue file, that i need to pass in my custom function.
2. If i use column, row, it say undefined.

Thanks in advance.

**Comment by gandesc** [comment]
Hi Alan,

In most cases, you don't need to add the ID as a rogue column, as you should have already added `dtRowId` in your table builder's select:
```
public function query()
    {
        return MyModel::select(\DB::raw('
            my_models.id as "dtRowId",
            my_models.name
        '));
    }
```

In your template, you should have your custom action:
```
"buttons": [
        "excel",
        "create",
        "edit",
        "destroy",
        "show",
        {
            "type": "row",
            "icon": "file-import",
            "class": "is-row-button",
            "event": "details",
            "confirmation": false
        }
    ],
```

And in your Vue page:
```
<vue-table class="box has-background-light is-paddingless raises-on-hover is-rounded"
            :path="path"
            id="some-id"
            @details="handleDetails"/>
```
where you need to declare the `handleDetails(event)` method, which will receive the event payload that will contain the `dtRowId`.

Hope that clears it for you.

**Comment by alanwhite2019** [comment]
@gandesc  Thank you. It was helpful. (y)

**Comment by aocneanu** [comment]
Can we close this?
