### ISSUE TITLE
How to re-render only specific column without re-rendering the table

### ISSUE THREAD

**Issue by gagishmagi** [laravel-enso/VueDatatable#128]
This is  a **bug | feature request**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

I am using this package to render vuedatable component
by the builder and the template.
After I do an store/update/delete operation on the datatable 
I hook onto the save/submit/edit/destroy events and fire the vuetable fetch() or getData()
functions to re-render the new data in the table. 

### Steps to Reproduce

1. Create a page and add a vuedatatable component
2. Create a template for its columns 
3. Try when add/update/remove data from the table with row and global buttons
but update each of the columns not with rows.

### Expected behavior

Would like to be able to re-render only specific column of the table

### Actual behavior

End up re-rendering the hole table or creating/editing/removing one the hole row but not the column.

**Comment by aocneanu** [comment]
When you say "specific column", you mean a specific cell?

**Comment by gagishmagi** [comment]
Yeah, we can start from there.

**Comment by aocneanu** [comment]
Give me more specifics, what "something that happens" may be?

How the table will be notified that something happens?

**Comment by gagishmagi** [comment]
The table will be notified by an event fired by laravel to some channel at the front end.
Something like "The field :field was updated" and the reload of the column will be fired.
Afterwords the some cells of the table will be updated.

**Comment by aocneanu** [comment]
This is an ... edge case to say the least :)

If you are already firing an event from the BE then use a slot on the specific column and make sure that you pass in the event the new values too. This way the component that you use in the slot can refresh without the table having to do anything else. And plus, you can use your own transitions for that.

But if I were you, I would use the event to trigger a new fetch in the table.

IT makes sense, performance wise, to reload 10 rows from a table with millions of entries. Loading only one column will still mean 10 rows and will not mean absolutely different in terms of performance (the query behind the hood will still have to filter, sort etc). So other than an exercise ("let's achieve that and see what happens") I really don't see any valid point in implementing this.

**Comment by gagishmagi** [comment]
Hey Adrian, thank you so much for a full and quick response.
I get what you are saying and I think it's fine to reload the hole table in my case,
but than I have another question, is there a quick way than to at least not show the overlay
when I fire the reload action? Because it will be a better user experience in my scenario,
I won't my user to feel that it's a "real time" app in the vuedatatable component and the loading 
overlay can kind of give it away... Thank you.

**Comment by aocneanu** [comment]
@gagishmagi 

>If you are already firing an event from the BE then use a slot on the specific column and make sure that you pass in the event the new values too. This way the component that you use in the slot can refresh without the table having to do anything else. And plus, you can use your own transitions for that.

If you're doing that then the overlay will not be displayed, because the request won't be managed by the table. You will see however, the red progress bar.
