### ISSUE TITLE
Dynamic search on vue-select-filter

### ISSUE THREAD

**Issue by alanwhite2019** [laravel-enso/VueDatatable#129]
Hello Guys.

Can you please guide me on how we can add dynamic search on vue-select-filter. I have a large number of records around 42K+

**Comment by gandesc** [comment]
Hi Alan,

VueSelectFilter uses the VueSelect component under the hood and you should be able to use its properties on the parent (filter) component.

Something along these lines should work for you:
```
<vue-select-filter multiple
    source="segment.myRoute.options"
    label="myLabel"
    :placeholder="__('Foo')"
    v-model="filters.ids"/>
```

where the route above should be a server-side vue select route.

Hope that helps.

**Comment by alanwhite2019** [comment]
Thanks. Let me try.

**Comment by alanwhite2019** [comment]
@gandesc  I tried it this way. 

**1. Make a route** 
`Route::get('get-prefixes', 'RateCardController@getUniquePrefixesList')->name('get-prefixes');`
**2. In my vue component, i added**
```
<vue-select-filter class="box"
                    source="/get-prefixes"
                        label="Prefix"
                        v-model="filters.prefix"/>
                    </vue-select-filter>
```
**What happens:**
I get the result in console BUT it shown an error

`[Vue warn]: Error in render: "TypeError: Cannot read property 'replace' of undefined"`
![image](https://user-images.githubusercontent.com/47517461/53332444-2cc95800-3915-11e9-8d99-544870d66c71.png)

**Comment by aocneanu** [comment]
`->groupBy('prefix')`

`label="Prefix"`

the latter starts with an uppercase

**Comment by alanwhite2019** [comment]
@aocneanu still same issue.

**Comment by alanwhite2019** [comment]
Thank you guys for the help. I sorted out the issue. It was a custom column 'prefix' that was collapsing with default 'name' attribute. 
Now i can populate select on first run but on searching query is getting **name** column in order by clause but i want it to be **prefix** (custom column name). Can you guide me on it.

**Comment by alanwhite2019** [comment]
I defined this
`protected $queryAttributes = ['prefix'];` in my controller and it works. 

Thank you.

**Comment by alanwhite2019** [comment]
@aocneanu Hi. Is there any possible issues we can face if we use **id** as non-numeric.

Actually what i am doing is, I am using **name** as my **id** because i need value instead of **id**.

**What I did is:**
1. Used query method
```
public function query() {
   return Cgrate_Tp_Destinations::**select(['tag', 'tag as id'])->groupBy('tag')**;
}
```
2. Used in vue file as:
`<vue-select-filter class="box"
                        source="/get-destination-tags"
                        **label="tag"**
                        title="Destination Name"
                        **trackBy="tag"**
                        value="filters.rate_cards.dstName"
                        **:limit="limit"** //50
                        v-model="filters.rate_cards.dstName"/>
    </vue-select-filter>`

Problem i am facing:
1. In case **id** is numeric it extract records based on limit, in my case its 50.
2. In case of **non numeric (text) id** it only extracts one record.

Expected behaviour:
- Select should also populate records when id is non-numeric.

My screen:
![image](https://user-images.githubusercontent.com/47517461/53640788-e9415780-3c4e-11e9-9a83-5c8fa184745f.png)

**Comment by alanwhite2019** [comment]
@aocneanu  I found the above problem is not because of numeric or non-numeric stuff, BUT happens when populating from other models.

Any guidance?
