### ISSUE TITLE
Add custom option in the template for the columns

### ISSUE THREAD

**Issue by shusharin** [laravel-enso/VueDatatable#130]
This is  a **feature request**.

### Prerequisites
* [V] Are you running the latest version?
* [V] Are you reporting to the correct repository?
* [V] Did you check the documentation?
* [V] Did you perform a cursory search?

### Description

Hi!
What you think about add custom option in column?
It will be more powerful customization then only  by slot.
For example:  "userData"

```
...
        , {
            "label": "Record duration",
            "name": "record_duration",
            "data": "calls.record_duration",
            "userData": {
            	"decorator": "formatSeconds",
            	"xlsFormula": "=TEXT(%d/24/60/60; 'HH:mm:ss')",
            	"someParam": {
            		...
            	}
            }
            "meta": [ 
                "slot"
            ]
        }
```
If you like it, i will prepare pull request.

**Comment by aocneanu** [comment]
It sounds interesting but I'm not sure that I fully understood. Why it's called `userData`?

Maybe a full example will  help.

**Comment by shusharin** [comment]
userData, Params or etc  - name its no matter. But it must be reserved field in column template. 
Sometimes, we need more freedom in customizing table cell.
Example:
Recently, I needed to decorate the output of data for several columns in a uniform way.

```
<div slot="c1" slot-scope="{row, column}">{{ decorator.formatSeconds(row[column.name]) }}</div>
<div slot="c2" slot-scope="{row, column}">{{ decorator.formatSeconds(row[column.name]) }}</div>
... etc
```

If we can use userData, we can use auto decoration. Then our vue template:
```
<vue-table 
    path="calls/init" 
    ref="callTable"
    ....
    @initialised="initialised" >
    <div v-for="(it, index) in autoDecorationSlots" :slot="it.name" slot-scope="{row, column}">{{ decoratorLib[it.userData.decorator](row[it.name]) }}</div>
    <div slot="col" slot-scope="{row, column}">ase slot for column {{column.name}}</div>
</vue-table>
```

Part of script section:
```
import decorators from '../decorators'
export default {
	data(){
		autoDecorationSlots: []
	},
	methods: {
	           initialised(){
                         // define slots with auto decoration
                         this.autoDecorationSlots = this.$refs.callTable.template.columns.filter(col => {
                             return col.meta.slot && typeof this.decoratorLib[(col.userData || {}).decorator] === 'function';
        	      }, this);
		}
	},
	created() {
		this.decoratorLib = decorators;
	}
}
```

Other way to use userData - some customizing when export xls, pdf etc.

**Comment by aocneanu** [comment]
@shusharin If I understood correctly, I believe that what you want is achievable by using Laravel accessors.

Define a `getDecoratedAttribute` on your model and put there the custom logic, then use the `appends` option in the template and use the decorated field.

**Comment by shusharin** [comment]
Yes, i know about this.
But, decorator may have many implementation, for example decorator for excel will be different then frontend.

**Comment by aocneanu** [comment]
Maybe you could post a full example in pseudocode here to point out a real life example and how to implementation would work.

Thanks

**Comment by aocneanu** [comment]
Will close for now, but still open for any concrete suggestions.
