### ISSUE TITLE
Wrong row count when expanding a row

### ISSUE THREAD

**Issue by ClCfe** [laravel-enso/VueDatatable#131]
Hello

If you expand a row, the row count (body.data.length) is wrong
https://github.com/laravel-enso/VueDatatable/blob/e6c1b9566d5b16127d4de59ac8696b78779fb946/src/resources/js/components/enso/vuedatatable/RecordsInfo.vue#L63

This is because addChildRow adds a new row in body.data
https://github.com/laravel-enso/VueDatatable/blob/e6c1b9566d5b16127d4de59ac8696b78779fb946/src/resources/js/components/enso/vuedatatable/TableBody.vue#L280

**Comment by aocneanu** [comment]
will be fixed in the next version
