### ISSUE TITLE
Inline edit

### ISSUE THREAD

**Issue by ebgreen** [laravel-enso/VueDatatable#136]
This is  a **bug | feature request**.

### Prerequisites
* [ ] Are you running the latest version?
* [ ] Are you reporting to the correct repository?
* [ ] Did you check the documentation?
* [ ] Did you perform a cursory search?

**Comment by aocneanu** [comment]
Very easy to achieve by using slots. (read the docs)

Create your own component around an input and post / patch to the needed endpoint on blur / keypress.enter or any other custom controls.

**Comment by ebgreen** [comment]
How hard is it would you say it is to add inline edit to certain fields in vuedatatables. I didn't see it in the docs and I haven't looked at it yet but it is a requirement of this new project I mentioned on the main ensue repository.

**Comment by ebgreen** [comment]
Figured it would be that easy. Thanks.

Thanks,


Eric Green

CTO

Cell: (619) 985 - 1270

Email: <admin@pitbullaudio.com>admin@pitbullaudio.com
<eric@expresslyweb.com>
