### ISSUE TITLE
Laravel 5.8.* is too high

### ISSUE THREAD

**Issue by phpguru** [laravel-enso/VueDatatable#137]
Are you using something specific to Laravel 5.8?

I ask because we are using Laravel 5.7 currently and cannot use this package, but it doesn't seem like there is any reason why it wouldn't work with Laravel 5.7 or even 5.6 for that matter.

**Comment by aocneanu** [comment]
Nop, nothing specific in this package. We're using 5.8 in Enso so we're keeping all the packages in sync. You can safely fork it and updated it locally.
