### ISSUE TITLE
Global button and action=href

### ISSUE THREAD

**Issue by ergonized** [laravel-enso/VueDatatable#139]
This is  a **feature request**.

### Description
I use release v 1.9.29 with Laravel 5.7 and independently (without Enso) and without vue-router.
I've created a global Create button like this:
    {
      "type": "global",
      "icon": "plus",
      "class": "is-primary",
      "action": "href",
      "routeSuffix": "create",
      "label": "Create",
      "event": "create"
    }

and I got this HTML:
```
<button data-v-7bcb17e9="" href="/vertical/create?" class="button has-margin-left-small is-primary"><span data-v-7bcb17e9="" class="is-hidden-mobile">
                    Create
                </span>
....
</button>
```

But I think it should be <a href="/vertical/create?" ...>
Or how can I process the 'click' on the 'Create' button and go to the path '/vertical/create' without vue-router?
I don't have this problem with 'edit' button (but it is 'row' button, not 'global')
`<a data-v-b090cb64="" href="/vertical/1/edit" class="button is-small is-table-button has-margin-left-small is-info"> ... </a>`

**Comment by aocneanu** [comment]
You should use the latest version, it renders <a> instead of <button> for both global and row buttons.

Also the path will be without "?" (at least that's how it seems by looking at the code:) )

**Comment by ergonized** [comment]
I got it. But latest version requires Laravel 5.8 and doesn't compatible with v 5.7. Right!?

**Comment by aocneanu** [comment]
Fork it and change this req

**Comment by aocneanu** [comment]
Or better, upgrade your app :)

**Comment by ergonized** [comment]
I got. Thanks!
