### ISSUE TITLE
lengthMenu changes fail

### ISSUE THREAD

**Issue by stotes** [laravel-enso/VueDatatable#141]
This is  a **bug and feature request**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
Changing the lengthMenu in template causes fail on tableData fetch 
``` 
"message": "SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '0' at line 1 (SQL: select id as \"dtRowId\" from `job_statuses` offset 0)",
```

### Steps to Reproduce
Change lengthMenu to an array [5,10] in Template JSON.

**PHP query**
```php
public function query()
{
     return JobStatus::select(\DB::raw('id as "dtRowId"'));
}
```
**Template JSON**
```json
{
    "routePrefix": "integration.tasker.queue",
    "crtNo": true,
    "lengthMenu":[5,10],
    "buttons": [
        {
            "type": "row",
            "icon": "code-fork",
            "class": "has-text-purple",
            "event": "load-queue-item",
            "label": "Load",
            "confirmation": true,
            "message": "Are you sure?"
        }
    ],
    "columns": [
        {
            "label": "ID",
            "name": "id",
            "data": "id",
            "meta": ["sortable"]
        }
    ]
}
```
### Expected behavior
Set menu options to 5,10.

**Feature request**
It would be very handy to have the ability to lock down controls and set explicit options.
Example: Ability to set via Template:
* Table length explicitly to x 
* Disable/enable particular controls(styles) and remove the menu

### Actual behavior
SQL error.

**Comment by br3athein** [comment]
came across this on v3.0.0 too - seems like a query w/ an `offset 0` in it fails due to the lack of `limit smth` keyword preceding it in an SQL query

@aocneanu I am currently wondering about why you closed the issue, any details?
