### ISSUE TITLE
On export-excel payload is null

### ISSUE THREAD

**Issue by degustadev** [laravel-enso/VueDatatable#142]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

I implemented VueDatatable as a separate module inside a Laravel project.
When clicking export excel global button, I generate a file on server-side, but then I get nothing on response event.

![Screenshot from 2019-04-04 10-33-24](https://user-images.githubusercontent.com/39300461/55541334-1c9b5a00-56c5-11e9-87dc-a3ae7683ca87.png)

As you can see the payload is null.

I created my own vue component based on bulma/VueTable but adding a listener for this event:

Vue part on core-table component:

![Screenshot from 2019-04-04 10-35-19](https://user-images.githubusercontent.com/39300461/55541462-5e2c0500-56c5-11e9-93a3-0a6625d8aa35.png)

![2](https://user-images.githubusercontent.com/39300461/55541490-6b48f400-56c5-11e9-9d1e-3a6e93241cf5.png)

But again, the `data` is `null` because there's no payload.

But when deleting or making any other action row (instead of global) I can return a json response with a message that will be popped up in a toastr.

I tried implementing my own button type `global` instead of using the export built in, but the same. Any global button contains a payload on response, why is that?.

What I want to achieve is, generate this file on server-side (which I managed to do now) but then return a json response that will be popped in a toastr up saying "Your file is generated, click here to download it" or something like this. Bu can't do it if payload is `null`.

### Steps to Reproduce

Implement VUeDatatable in blade view configured with export-excel button and click it.

### Expected behavior

There's payload on response

### Actual behavior

There is no payload on response

**Comment by aocneanu** [comment]
What version are you using?

The package will attempt to send to exported file on your email if used outside enso.

**Comment by degustadev** [comment]
Hello aocneanu,

I'm using it outside of enso and currently using the last version.

In the end I fixed it avoiding vue to download the file, but being directly php who handles it. Completely other solution.
