### ISSUE TITLE
Scoped Slot Example

### ISSUE THREAD

**Issue by stotes** [laravel-enso/VueDatatable#143]
This is  a **feature request**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
Would it be possible to show an example usage of ```slot``` meta in the documentation?

**Comment by stotes** [comment]
Maybe it's redundant as it's already explained in the documentation, but I know many (including myself) like to see an example usage.


**Template JSON** 
```json
{
    "routePrefix": "tableExample",
    "crtNo": true,
    "columns": [
        {
            "label": "ID",
            "name": "id",
            "data": "id",
            "meta": ["sortable"]
        },
        {
            "label": "ExampleSlot",
            "name": "example",
            "data": "example",
            "meta": ["meta"]
        },
    ]
}
```
**Parent Component Template**
```vue
<vue-table
    id="queue-list"
    :path="'tableExample/initTable'"
    v-on="$listeners"
>
    <template v-slot:example="exampleSlot">Example {{exampleSlot.row.id}}</template>
</vue-table>
```

**Comment by aocneanu** [comment]
Sure.

More than 95% of the features from documentation are represented at least in one place in Enso's codebase, you just have to browse through its files a bit.

[avatar in user table](https://github.com/enso-ui/ui/blob/master/src/bulma/pages/administration/users/Index.vue#L4)

[data import indicators highlight](https://github.com/enso-ui/ui/blob/master/src/bulma/pages/dataimport/Index.vue#L64)

[flag in localisation table](https://github.com/enso-ui/ui/blob/master/src/bulma/pages/system/localisation/Index.vue#L4)

[permission type tag](https://github.com/enso-ui/ui/blob/master/src/bulma/pages/system/permissions/Index.vue#L4)

And probably there are more.
