### ISSUE TITLE
Name and Icon Options

### ISSUE THREAD

**Issue by stotes** [laravel-enso/VueDatatable#145]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
**icon**
Setting option ```icon``` in the template, fails with the following message
```json
{ "message": "Unknown Attribute(s) Found: \"icon\"" }
```
**name**
The option ```name``` in the template, is meant to provide a title for the table as stated in the documentation. 
``` name, optional, string, the title used for the table. If not given, no title is used```

However, it currently does not provide a title and I am unable to find any reference to the ```state.template.name``` in the ```src/bulma/parts/TableHeader.vue``` file, or anywhere in the UI table package.

**Template**
```json
{
    "routePrefix": "exampleTable",
    "crtNo": true,
    "icon": "list-alt",
    "name":"Example Title",
```

**Comment by aocneanu** [comment]
The icon was deprecated and the name is used only for generating excel files.

@gandesc maybe you could update the docs on this.

**Comment by gandesc** [comment]
I have updated the docs.
