### ISSUE TITLE
Case insensitive search in MySql

### ISSUE THREAD

**Issue by BKirev** [laravel-enso/VueDatatable#146]
This is  a **feature request**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

Hey there.
First of all, thanks for the awesome table!
I'm wondering if it's possible to do case insensitive search with MySql? Already read about **comparisonOperator** and ILIKE, but that won't help with MySql. Is there any other way or I should modify the package itself?

Regards!

**Comment by stotes** [comment]
If you add COLLATE UTF8_GENERAL_CI to your column's definition, it will work case insensitive.

```ALTER TABLE trees 
 MODIFY COLUMN title VARCHAR(…) CHARACTER 
 SET UTF8 COLLATE UTF8_GENERAL_CI. 
```
This will also rebuild any indexes on this column so that they could be used for the queries without leading '%'


It may also be possible to modify the MySQL driver:
```php
'mysql' => array(
    'driver'    => 'mysql',
    'host'      => 'localhost',
    'database'  => 'database',
    'username'  => 'root',
    'password'  => '',
    'charset'   => 'utf8',
    'collation' => 'utf8_unicode_ci',
    'prefix'    => '',
),
```
You can create a different connection for the table query:
```php
'mysql-collation' => array(
    'driver'    => 'mysql',
    'host'      => 'localhost',
    'database'  => 'database',
    'username'  => 'root',
    'password'  => '',
    'charset'   => 'utf8',
    'collation' => '<your collation>',
    'prefix'    => '',
),
```
And use that connection on your query:
```php
$users = DB::connection('mysql-collation')->select(...);
```
You can also set a connection like this:
```php
$posts = new Posts();
$posts->setConnection('mysql-collation');
$posts->select(...);
```

**Comment by stotes** [comment]
An example of one of my VueDataTable's using ```collate```. 
```php 
protected $templatePath = __DIR__.'/../Templates/TaskerQueueTable.json';

    public function query()
    {
        return JobStatus::select('job_statuses.*')->from(
            \DB::raw('('.'SELECT *, id as "dtRowId", params->>"$.name" COLLATE utf8mb4_unicode_ci as job_name FROM job_statuses'.') as job_statuses')
        )->withCount('logs', 'errors')->orderBy('job_statuses.id', 'DESC');
    }
```

**Comment by BKirev** [comment]
Thank you for the suggestions.

So for the MySql driver I do have an case insensitive charset selected:


```php
'mysql' => [
            'driver' => 'mysql',
            ...
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'prefix_indexes' => true,
            'strict' => true,
            'engine' => null,
            'options' => extension_loaded('pdo_mysql') ? array_filter([
                PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
            ]) : [],
]
```

I also tried doing this:


```php
return Order::select(DB::raw("
            *, id as 'dtRowId',
            JSON_UNQUOTE(JSON_EXTRACT(shipping_address, '$.name')) COLLATE utf8mb4_unicode_ci as shipping_name,
            JSON_UNQUOTE(JSON_EXTRACT(shipping_address, '$.city')) COLLATE utf8mb4_unicode_ci as shipping_city
        "));
```
Both of them won't do case insensitive search. I was wondering if it has something to do with the fact that these are JSON fields, but it works fine for case sensitive queries.

**Comment by stotes** [comment]
What does your table definition look like?

> Thank you for the suggestions.
> 
> So for the MySql driver I do have an case insensitive charset selected:
> 
> ```
> 'mysql' => [
>             'driver' => 'mysql',
>             ...
>             'charset' => 'utf8mb4',
>             'collation' => 'utf8mb4_unicode_ci',
>             'prefix' => '',
>             'prefix_indexes' => true,
>             'strict' => true,
>             'engine' => null,
>             'options' => extension_loaded('pdo_mysql') ? array_filter([
>                 PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
>             ]) : [],
> ]
> ```
> 
> I also tried doing this:
> 
> ```
> return Order::select(DB::raw("
>             *, id as 'dtRowId',
>             JSON_UNQUOTE(JSON_EXTRACT(shipping_address, '$.name')) COLLATE utf8mb4_unicode_ci as shipping_name,
>             JSON_UNQUOTE(JSON_EXTRACT(shipping_address, '$.city')) COLLATE utf8mb4_unicode_ci as shipping_city
>         "));
> ```
> 
> Both of them won't do case insensitive search. I was wondering if it has something to do with the fact that these are JSON fields, but it works fine for case sensitive queries.
> 
> EDIT:
> I've found why it's not acting as expected.
> I have this in the template:
> 
> ```json
>    {
>       "label": "Shipping Name",
>       "name": "shipping_name",
>       "data": "shipping_address->name",
>       "meta": [ "slot", "searchable" ]
>     },
>     {
>       "label": "Shipping City",
>       "name": "shipping_city",
>       "data": "shipping_address->city",
>       "meta": [ "sortable", "searchable" ]
>     },
> ```
> 
> which produces:
> 
> ```sql
> select
> *, id as 'dtRowId',
> JSON_UNQUOTE(JSON_EXTRACT(shipping_address, '$.name')) COLLATE utf8mb4_unicode_ci as shipping_name,
> JSON_UNQUOTE(JSON_EXTRACT(shipping_address, '$.city')) COLLATE utf8mb4_unicode_ci as shipping_city
> from `orders` where (`order_status_url` LIKE '%varn%' or `name` LIKE '%varn%' or json_unquote(json_extract(`shipping_address`, '$."name"')) LIKE '%varn%' or json_unquote(json_extract(`shipping_address`, '$."city"')) LIKE '%varn%' or `total_price` LIKE '%varn%' or `confirmed` LIKE '%varn%' or `financial_status` LIKE '%varn%') limit 10 offset 0
> ```
> 
> ```json
> "data": "shipping_address->name",
> ```
> 
> produces
> 
> ```sql
> json_unquote(json_extract(`shipping_address`, '$."name"'))
> ```
> 
> but if I switch `data` to `shipping_name`, that won't be searchable, since it's not an actual column in the DB.

**Comment by aocneanu** [comment]
Did you figure this out?

With the default laravel connection config I always got case insensitive search.

**Comment by BKirev** [comment]
Hey!

Sorry for the late reply. I believe the issue comes from the json field itself and especially the way I'm parsing it. However, I've re-structured my tables structure because I found flaws anyway.

I can confirm that on default laravel connection config the search is case insensitive on regular fields.
