### ISSUE TITLE
Create a dynamic table class that can be used to show multiple tables.

### ISSUE THREAD

**Issue by paulmaessen** [laravel-enso/VueDatatable#147]
This is  a feature request/question

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

We need to implement lot's of tables in our application. Would you recommend to setup a dynamic table which is filled with configuration data (for example stored in the database)
What would be the best way to set this up? The  reason to use this dynamic table is the ability to add a new table without adding code, just a configuration.

### Steps to Reproduce
Not applicable

### Expected behavior
Having a single set of table-controllers and a single table class that can be configured to host multiple tables.

### Actual behavior
Not applicable

**Comment by aocneanu** [comment]
I'm not sure that I understand.. do the tables have anything in common ? (model, template etc)

If not, I would definitely **not** recommend setting up a dynamic endpoint to serve all.

In our apps we have tens of tables and each uses its own endpoint / set of resources. The same for forms and other FE elements.

**Comment by paulmaessen** [comment]
The tables have a dynamic model in common, so yes i want to create a dynamic endpoint. The reason for this is the fact that I want the user to create additional tables without  needing to change the code.
So the configuration and definition of the table, model and form will be stored in a database and the dynamic list will be displayed by adding the id for the definition to the controller and then create the table...

**Comment by aocneanu** [comment]
I think I got it now. The way I would go about it is:

- having multiple json templates on disk
- having a query builder class for each template
- sending relevant meta by using an `init-params` prop in the table init request
- having only one controller
- interpreting the meta in BE (one table builder class) to decide which table template and which query builder class are needed. This cand be done using the `templatePath()` and `query()` methods available in the builder.

For that to work I would have to modify the FE and add an `initParams` prop that would be added to the init request if it's not null.

**Comment by paulmaessen** [comment]
Yes, thats how I was thinking it could be implemented. I only created a single query builder class that is retrieving the query-details from the configuration also.

If this initParams-property would be available then I just have to add this in the template for each list and I do get this information available in the request on the server?
