### ISSUE TITLE
Demo, show code not working

### ISSUE THREAD

**Issue by ganjarsetia** [laravel-enso/VueDatatable#149]
I opened the demo [https://www.laravel-enso.com/examples/table](https://www.laravel-enso.com/examples/table) and try to click "Show Code" but its not working, I tried in another browser, the result is same.

![image](https://user-images.githubusercontent.com/3258090/56867390-c7760e00-6a0e-11e9-8e3b-e9a2964b48d3.png)

If I made mistake reporting this issue, please close & ignore the issue.

**Comment by aocneanu** [comment]
Hi. You did not make a mistake reporting it but the issued belongs to laravel-enso/examples and you should also use the issue template.

**Comment by ganjarsetia** [comment]
Hi, thanks for the reply & the good work.
Oh sorry for my mistake, I didn't know if its belong to the examples.
Now I will follow [Enso#213](https://github.com/laravel-enso/Enso/issues/213) for updates.

Feel free to close the issue.
