### ISSUE TITLE
Possibility to set condition if a row is deletable/editable

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/VueDatatable#16]
Use case:
I have a table with rows with a entry_date
Only rows of the current month should be editable - other rows are write protected.

Do you have an idea how to manage this?

**Comment by aocneanu** [comment]
The action buttons are build based on users permissions.

You can achieve though what you need with what's implemented, but you need to walk the extra mile for that :). I'll describe below one approach:

- define a custom edit button for this table that will emit an event. You can use the template for the current edit button from the `datatable.php` config
- when the event is fired call a method where you do your validations and either show a relevant toast when you don't want to allow the action, or proceed further with the `$router`. For a cleaner implementation in the FE maybe set a flag on the model using a laravel accessor and the `appends` attribute in vuedatatable.
- back this up with a Policy on the BE where you set the rules for editing/updating an entry.

It's not impossible to develop a dedicated feature tto allow showing / hiding buttons dinamically, but I did't find yet a nice and clean way to do it. If you have an idea don't hesitate to tell me.

However, even with the dynamic buttons, you would still have to write a policy on the BE for this situation.

Cheers

**Comment by mauthi** [comment]
Solved it like you described the changes - it works. Thx

**Comment by heyner29** [comment]
It is still not possible to condition the buttons?

**Comment by aocneanu** [comment]
>...I did't find yet a nice and clean way to do it. If you have an idea don't hesitate to tell me.
