### ISSUE TITLE
How to include the name of a foreign key?

### ISSUE THREAD

**Issue by dcastrili** [laravel-enso/VueDatatable#19]
Hi,

Is there any way to add the name of the foreign key in the query? how to handle the relationship in the raw query?

**Comment by aocneanu** [comment]
https://github.com/laravel-enso/Core/blob/master/src/app/Http/Controllers/User/UserTableController.php

Is this what you’re looking for?

**Comment by dcastrili** [comment]
Yes, Doing some testing so far.
