### ISSUE TITLE
Warning: Avoid mutating a prop directly (when using filters)

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/VueDatatable#2]
I get the following warning:
`[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "filters"`

My code:
```
<vue-table :path="path"
        	:i18n="__"
	        id="partneraccountentries"
	        :removable="removable"
	        :filters="extraFilters"
	        ref="paeTable">
</vue-table>

```
```
export default {
    	...
    	data: function() {
    		return {
    			...
	    		"extraFilters": {
				    "partner_account_entries": {
				        "user_id": 18,
				    },
				},
				...
	        };
    	},
```

**Comment by aocneanu** [comment]
This is strange, can you give me also a line where the filters are mutated? `filters` is a read only prop from the table components point of view.

**Comment by mauthi** [comment]
"can you give me also a line where the filters are mutated?“

what do you need - don’t unterstand this :)?

**Comment by aocneanu** [comment]
When you get the warning in the console you should also get the js file and line number where this happens.

**Comment by mauthi** [comment]
Sorry, should read your text more carefully

Here is the full output:

```
[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "filters"

found in

---> <VueTable> at resources/assets/js/components/enso/vuedatatable/VueTable.vue
       <Index> at resources/assets/js/pages/enso/netwerker/partneraccountentries/Index.vue
         <Router> at resources/assets/js/pages/enso/layout/Router.vue... (2 recursive calls)
           <AppMain> at resources/assets/js/pages/enso/layout/AppMain.vue
             <Root>
```

**Comment by aocneanu** [comment]
I identified and corrected the problem. The component tried to save in localStorage also the states of the filters/intevals. I removed this.

If we need saving the filters state for a specific page this must be implemented locally, like in the old table package.
