### ISSUE TITLE
How to install it step by step !

### ISSUE THREAD

**Issue by AEK-BKF** [laravel-enso/VueDatatable#20]
Hi,
Thank you so much for this nice package.
I tried to install it but I don't know how to start ! please could you show us step by step ?
1. Download.
2. Publish.
3. Config.
4.. etc

Thanks.

**Comment by aocneanu** [comment]
Hi,

In the coming days we'll add this section to the readme.

I'll leave this open until then.

**Comment by AEK-BKF** [comment]
Thank you.
We're waiting ... :)

**Comment by gandesc** [comment]
Hi @AEK-BKF , I've updated the documentation.

Please let us know if you find something's missing or have suggestions for improvement.

Am going to close this for now.
