### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by schtips** [laravel-enso/VueDatatable#24]
Hi there and thank you for the component.

Just a heads-up that using this component independant of laravel/enso project needs a lot more 
setup than described in the readme.
Don't know if it's in scope, but I'll try to resume here what needs to be done:

1. In the documentation, on step 4 there is a Toastr import that is not in the assets for this package. I assume that this package should have laravel-enso/vuecomponents as a dependency, since there is where the Toastr component lives.
2. There are a few npm dependencies missing for the missing icons if using the example provided:
- @ fortawesome/fontawesome
- @ fortawesome/fontawesome-free-solid
- @ fortawesome/fontawesome-free-brands
This icons need to be imported at some point during the app like this:
import { faUpload } from '@fortawesome/fontawesome-free-solid/shakable.es';
fontawesome.library.add([faUpload]);
This has to be done for any icons that will be used in the datatables (or referenced by table json that gets loaded into the controller).
3. @ fortawesome/vue-fontawesome needs to be installed with npm/yarn, imported in the bootstrap file and the component registered globally:
```
import FontAwesomeIcon from '@fortawesome/vue-fontawesome';
Vue.component('fa', FontAwesomeIcon);
```

Hope it helps someone.

**Comment by aocneanu** [comment]
@gandesc please add the above to the docs.

@schnitzel25 thank you!
