### ISSUE TITLE
Feature request: Define initial settings for tables

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/VueDatatable#25]
It would be nice if it's possible to set default values for tables, like:
- order by column
- visible columns
- ...
(all things which are stored in preferences)

**Comment by aocneanu** [comment]
I not convinced that we would have a real benefit in this.

**Comment by mauthi** [comment]
Typical examples where this would be useful: 
- Something where you insert chronological entries and you are intereseted in the newest entries at first view.
- Users table: At first view you are intereseted in users ordered by lastname?
- ...

**Comment by aocneanu** [comment]
Why don't you customise the initial query ?

**Comment by mauthi** [comment]
If this is possible (and the arrows on column header are shown correctly) that would be a solution.
I will try this later.

**Comment by aocneanu** [comment]
The arrows will not display, of course :)

**Comment by mauthi** [comment]
At the moment for me it's ok without arrow - but I would leave this open because I think default sort_order is a standard onfig option for table components (e.g. https://datatables.net/reference/option/order)

**Comment by aocneanu** [comment]
Taking in consideration that you can set a default sort from the controller, and probably most of the users will have their own config with just two click, I would find adding this to the template and the overhead for the builder somehow redundant and inefficient.

But maybe in the future we will think of something like this.

I'll close this for now.
