### ISSUE TITLE
Feature request: Define pre defined column "views" for tables

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/VueDatatable#26]
It would be nice if we can store pre defined "column views" for tables.

Example:
- I have a table for customers with > 20 columns
- Sometimes I need address, phone, eg. of customer - sometimes I need revenue, hours tracked, ... 
- I don't want to create 2 vue-tables in my application
- It would be easy if we can define different views:
1) contact view: show customer number, name, address, phone, ... - hide revenue, hours tracked, ...
2) accounting view: show customer number, name, revenue, hours tracked, ... - hide address, phone, ...

Do you know what I mean?

**Comment by gandesc** [comment]
What's wrong with having distinct templates/controllers ?

IMO, I think it's cleaner to have a specialized table for each case, since if you're thinking of re-using the same table controller / select query, you're going to retrieve data, maybe make joins, compute attributes, etc you don't really need.

**Comment by aocneanu** [comment]
I think that we can even reuse one controller with two or more templates.

**Comment by mauthi** [comment]
yes and no - sometimes it's cleaner but in the case of customer I need:
- 3 different " table views" for 3 different usecases (at the moment - maybe some more)
- 1 export with all columns

In my point of view a customer is a customer and therefor it should be on customer table to display them. I know this from an other framework and that was the reason why I added this as feature request.

**Comment by mauthi** [comment]
> I think that we can even reuse one controller with two or more templates.
That would be a compromise variant

So I would create a customer-table-component and set the template path as property (don't know if this is possible at the moment?)?

**Comment by aocneanu** [comment]
@mauthi,

To use a table controller with two template you'll have to define the two routes, and the corresponding methods. Let's use the `OwnerTableController` as an example.

For the routes instead of:
```
Route::get('initTable', 'OwnerTableController@init')->name('initTable');
```
you would do :

```
Route::get('initTableOne', 'OwnerTableController@initOne')->name('initTableOne');
Route::get('initTableTwo', 'OwnerTableController@initTwo')->name('initTableTwo')
```
For the controller you will write your own `init()` methods and give up the `DataTable` trait.

```
class OwnerTableController extends Controller
{
    use Excel;

    private const TemplateOne = __DIR__.'/../../../Tables/ownersOne.json';
    private const TemplateTwo = __DIR__.'/../../../Tables/ownersTwo.json';

    public function query()
    {
        return Owner::select(\DB::raw('id as "dtRowId", name, description, is_active, created_at'));
    }

    public function initOne()
    {
        $template = new Template(self::TemplateOne);

        return $template->get();
    }

    public function initTwo()
    {
        $template = new Template(self::TemplateTwo);

        return $template->get();
    }

    public function data(Request $request)
    {
        $table = new Table($request, $this->query());

        return $table->data();
    }
}
```

**Comment by mauthi** [comment]
thx for the description, will take a look on it in the next days
