### ISSUE TITLE
If Expanded row has one column it never toggle open but plus icon shown

### ISSUE THREAD

**Issue by shonhor22** [laravel-enso/VueDatatable#29]
how fix this?

**Comment by shonhor22** [comment]
Thanks. 
I have a question. i changed some .vue file that stored in resource/asset/js folder.
translated placeholder added button etc. But when run composer update all of these overwritten. How avoid this, please answer me a hint

**Comment by aocneanu** [comment]
please open a dedicated ticket on the enso repo and try to provide as many details as you can.
