### ISSUE TITLE
Possibility to manipulate data

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/VueDatatable#30]
At the moment it's only possible to use a raw query for VueDatatable - makes sense in combination with searching, sorting, ...

I'm looking for a possibility to manipulate the data before it is returned.
Let me explain this with a simple example (my real use cases are a little bit more difficult but with this example you should get the idea):
- I have a customers table in my application
- Each customer has an output name
-- if customer_type == business then output_name = oranization
-- if customer_type == consumer then output_name = firstname." ".lastname
- at the moment I have both
-- a getOutputNameAttribute() function on my model which creates the output_name like described above AND
-- a IF(xxx) in my raw sql query which creates the output name based on the same logic on database layer
- I would like to have the creation for output name just on php layer - therefore it would be nice if I can loop through the result data and manipulate data (or better use the model class)

Is this somehow possible at the moment or do you have an idea for future?

**Comment by aocneanu** [comment]
Are you using the ‘appends’ option already?

**Comment by mauthi** [comment]
no?

**Comment by aocneanu** [comment]
The easiest way to achive what you want is by using the `appends` option available in the template. This option is made exactly for the purpose of appending laravel accesors.

So want you want to do is add to the template.json root `appends = ['output_name']` and then add a column to the template for `output_name` and you're done.

Note that this column should not be searchable nor sortable.

If you need also sorting then you can use an Enum. You can find a working example in the project already, just dig around https://github.com/laravel-enso/PermissionManager/blob/master/src/app/Tables/permissions.json#L39.

If you hit any walls let me know

**Comment by mauthi** [comment]
will give that a try in the next days - thx.

Is there a possibility to get this column searchable?

**Comment by aocneanu** [comment]
Nope, because it’s not an actual column.

**Comment by mauthi** [comment]
Thx - worked for me and now I know why sorting/searching is not possible. 
But in combination with #33 I would be able to solve this for me.
