### ISSUE TITLE
Feature request: Add searchable, hidden columns

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/VueDatatable#33]
At the moment it's only possible to search within displayed columns - because the sort() function in Table Class loops through columns array.
```
$this->columns->each(function ($column) {
            if ($column->meta->sortable && $column->meta->sort) {
                $this->query->orderBy($column->data, $column->meta->sort);
            }
        });
```

Sometimes it would be necessary to search other columns - let me explain this with an example:
- In my table I have a icon column for url and e-mail (to save space I don't want to output full url, only clickable icon)
- But it would be nice to search for url too

Possible solution:
- add "hidden" columns to table config **(or better add another config value equal to "appends")** where we can define columns which are sortable but not rendered in table?
- should be an easy solution and useful for everybody?

**Comment by aocneanu** [comment]
I suppose that I can add a `hidden` attribute in the column's `meta` options to achieve this. But I see as extremely counter intuitive to magically filter by a column that does not exist in the table.

But maybe you're lucky because I'm working at #34, and this will allow to show whatever you want instead of the column' value, and still keep the column searchable, sortable.

**Comment by mauthi** [comment]
#34 looks good for some use cases, but let me give you another example which would not be possible with #34 

- In my customers table I use name (accessor on customer model) 
- output name is either column organization or a combination of firstname or lastname, depends on customer type
- here it would be good to show name and search within organization, firstname and lastname

Do you think I can solve that with #34 as well?

**Comment by aocneanu** [comment]
This exemple is better:)

We already have a "hidden" meta attribute, I'm thinking of "disabled" for this situation.

**Comment by aocneanu** [comment]
Finally I decided to go with the `rogue` attribute. Just add it to the column's meta.

**Comment by mauthi** [comment]
thx - it works
