### ISSUE TITLE
Feature request: Tooltip for icon columns

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/VueDatatable#35]
It would be nice if we can set a tooltip for columns with meta = icon
- Easy solution (first step): Same tooltip for every row
- Second step: Define another column to read the tooltip

Example:
- Icon for Url
- Tooltip: "Click here to open www.test.com"

**Comment by aocneanu** [comment]
#34 will allow you to achieve this also.

**Comment by aocneanu** [comment]
closed with 192725d

**Comment by mauthi** [comment]
can you please give me an example how do use #34 and tooltips?

**Comment by aocneanu** [comment]
Just put in the column's meta the `slot` tag and in the FE you will have a scoped slot with the name of the column that will pass you the `value` of the row and the `column` object.

```
<vue-table .....>
     <span slot="tooltip_column"
             class="icon is-small">
             scope-slot="{ value, column }"
            ....do something with the column object if you need>
            <fa icon="icon" v-tooltip="{{ value }}"></fa>
     </span>
</vue-table>
```

**Comment by mauthi** [comment]
I tried this but I think there is something wrong - here is my changed code:
```
<vue-table .....>
     <span slot="tooltip_column"
             class="icon is-small"
             slot-scope="{ value, column }">
            <a :href="value"><fa icon="icon" v-tooltip="value"></fa></a>
     </span>
</vue-table>
```

- Changed `scope-slot` to `slot-scope`
- Changed `{{ value }}` to `value`
- value seems to be empty (column is not empty and contains column data)

Can you please help me again?

**Comment by aocneanu** [comment]
With the lastest version you get row instead of value.

Sent from my iPhone

**Comment by mauthi** [comment]
thx, now it works - using row instead of value would have been my next suggestion :)
