### ISSUE TITLE
Plus icon (responsive) not visible if "crtNo": false (bug?)

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/VueDatatable#36]
Is this a bug? If I don't use crtNo the table has a horizontal scrollbar because there is no column available for plus icon?

Is there a solution for that? I don't want to show a row number here because the second column is the customer_number and the 2 numbers would confuse users.

**Comment by mauthi** [comment]
![screenshot 2018-03-10 12 28 14](https://user-images.githubusercontent.com/7204559/37241742-87e05d78-245e-11e8-9072-e83b131c22be.png)

**Comment by aocneanu** [comment]
This is expected behaviour but should be corrected
