### ISSUE TITLE
Table adds empty column if there is now row-button

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/VueDatatable#4]
If I don't use a button for a table row there is one additional column rendered without column header - see:

<img width="213" alt="screenshot 2017-12-10 14 49 46" src="https://user-images.githubusercontent.com/7204559/33805471-ce2da5c4-ddb9-11e7-8266-57fe048378ff.png">

**Comment by mauthi** [comment]
2 other things in combination with that:
![screenshot 2017-12-13 15 35 51](https://user-images.githubusercontent.com/7204559/33944121-76bb1e2a-e01b-11e7-9b4e-9291168b6bf6.png)

- Total row is not responsive
- Button in 2nd row needs a little spacing or padding (minor)

**Comment by mauthi** [comment]
Problem with not responsive total row is solved now but the following problem still exists:
https://user-images.githubusercontent.com/7204559/33943910-c2cef76a-e01a-11e7-9db1-69966d1132f5.png

**Comment by aocneanu** [comment]
this is strange

![image](https://user-images.githubusercontent.com/16073274/34319214-269b42a4-e7e5-11e7-8efc-dae54a201a0d.png)

Try a browser cache clear.

**Comment by mauthi** [comment]
I have cleared everything.
It works if I have a column with buttons like in your screenshot - but it doesn’t work if I don’t need the action column like in my screenshot.

**Comment by aocneanu** [comment]
We also had a problem with buttons validation when the optional `buttons` property is missing from the json template.

Fixed both.

**Comment by mauthi** [comment]
looks good now
