### ISSUE TITLE
Change translation keys of records info

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/VueDatatable#42]
```
        fromInfo() {
            return `(${this.i18n('filtered')} ${this.i18n('from')} ${this.body.count} \
            ${this.i18n('total')} ${this.i18n('records')})`;
        },
```
In English it's ok: `filtered from 4711 total records`
But in German I'm not able to translate it with 4 words - should be `gefiltert aus insgesamt 4711 Einträgen`

1st solution:
- combine `filtered from` and `total records`
2nd solution:
- invent something like `filtered from %s total records` (can be useful for other use cases - and I know this kind of translations with placeholders from other systems)

**Comment by aocneanu** [comment]
Maybe we should have a config option for this.

**Comment by aocneanu** [comment]
I forgot about this.. Did your 1st solution.
