### ISSUE TITLE
Datatable how add multiple selected values in 1 column

### ISSUE THREAD

**Issue by shonhor22** [laravel-enso/VueDatatable#44]
This is  a **bug | feature request**.

### Prerequisites
* [ ] Are you running the latest version?
* [ ] Are you reporting to the correct repository?
* [ ] Did you check the documentation?
* [ ] Did you perform a cursory search?

### Description

i have to add column that contain multiple options.
i used group_concat. but datatable's total value changed wrong cause of group by
### Expected behavior

If possible add a column to menus index datatable show which roles selected.

**Comment by gandesc** [comment]
Hi, 
It's a bit tough to follow your description, generally it helps if you also add screenshots and/or code snippets.

Also, the usage of group by is considered a not so good practice.

To the point, if I understand your need correctly, you could use an appended attribute on your main model, and the appends functionality for DataTables:

 [model](https://laravel.com/docs/5.6/eloquent-serialization#appending-values-to-json)
 [datatable docs](https://github.com/laravel-enso/VueDatatable#template)

Keep in mind the appended columns should be excluded from searching (` 'notSortable'        => [4],`)

**Comment by aocneanu** [comment]
@gandesc meant that you should not add to the column's meta the `sortable` tag.

@shonhor22 about the new column in the menus table.. imagine an application with 30 roles, and probably some of the menus will be available to all the roles. How would this look in the table?

**Comment by aocneanu** [comment]
I guess we can close this.

**Comment by shonhor22** [comment]
Sorry i have no idea to implement this task.
If i append new attribute to model this will not return TableControllers query() method.
Example in MenuTableController 
public function query()
    {
        return Menu::select(\DB::raw(
            'menus.id as "dtRowId", menus.name, menus.icon, menus.has_children, menus.order,
            parent_menus.name as parent, menus.link, menus.created_at, menus.updated_at'
        ))->leftJoin('menus as parent_menus', 'menus.parent_id', '=', 'parent_menus.id');
**->leftJoin('menu_role', 'menus.id', '=', 'menu_role.menu_id')**
**->leftJoin('role', 'role.id', '=', 'menu_role.role_id')**
    }
Now i want to add column that role.name. maybe 2 role selected show admin, supervisor in 1 column.

Sorry my english not well

**Comment by aocneanu** [comment]
https://laravel.com/docs/5.6/eloquent-mutators#accessors-and-mutators

Do the following:

Menu.php

```
public function getRolesLabelAttribute()
{
      return $this->roles->pluck('name')->implode(', ');
}
```

then, in the roles.json (table template)
```
.....
"appends": ["roles_label"],
.....
"columns": [
....
     {
            "label": "Roles",
            "name": "roles_label",
            "data": "menus.roles_label",
            "meta": []
        }
....

]
```

Now you're all set:)

**Comment by shonhor22** [comment]
Followed instruction but nothing return on Roles column.
I printed log of executed query there were 
[2018-03-29 23:03:43] local.INFO: select `roles`.*, `menu_role`.`menu_id` as `pivot_menu_id`, `menu_role`.`role_id` as `pivot_role_id` from `roles` inner join `menu_role` on `roles`.`id` = `menu_role`.`role_id` **where `menu_role`.`menu_id` is null**  .

**Comment by gandesc** [comment]
The query is not really relevant if you're talking about the tableQuery, since the DT builder appends the data at a later step.

Can you try with:
```
 {
            "label": "Roles",
            "name": "rolesLabel",
            "data": "rolesLabel",
            "meta": []
        }
```
Also, make sure the attribute/getter is working. You may test in `tinker`, where if you do `json_encode(Menu::first())` you should see the appended attribute in the result.

**Comment by shonhor22** [comment]
I think appended column retrieve data by belowing auto generated query. But query check menu_id is null. So no data retrieved.
select `roles`.*, `menu_role`.`menu_id` as `pivot_menu_id`, `menu_role`.`role_id` as `pivot_role_id` from `roles` inner join `menu_role` on `roles`.`id` = `menu_role`.`role_id` where `menu_role`.`menu_id` is null

**Comment by aocneanu** [comment]
Ok, here is the problem. For the appends to happen you will have to bring the model’s id column. You have it now, but it’s aliases to dtrowid, and the datatable needs that, so just add to the select ‘menus.id’. And drop the Distinct, it does nothin in this query.

**Comment by Cactusx09** [comment]
Otherwise it's an error when try to get dtRowId from empty SQL Table?
