### ISSUE TITLE
Totel row not aligned correctly

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/VueDatatable#45]
This is  a bug.

### Description
If you change alignment the total row stays centered.

### Steps to Reproduce
Open table
Add meta total to at least one column
Align columns to right

### Expected behavior
Total row column should have the same alignment as table column

### Actual behavior
Total row column has center alignment

![screenshot 2018-03-29 12 58 22](https://user-images.githubusercontent.com/7204559/38085514-1b0af80a-3351-11e8-9bc4-0c5bbe415a60.png)

**Maybe we should think about alignment-settings on column layer (because for text columns left alignment makes sense - for decimal total columns right alignment is better)?**

**Comment by aocneanu** [comment]
I'm thinking that money should always be aligned right...

**Comment by mauthi** [comment]
I think you should be able to set the alignment per column.
Per default
- text left
- boolean center
- money right

I’m not sure if we need the alignment dropdown than anymore.

**Comment by aocneanu** [comment]
Yeah, will think about this in the future. The only way I see this good for UI is if all the customization would all be in the FE. So we need to think at some nice / clever / discrete control to place somewhere, somehow in the table header, and maybe this control would toggle the three classes.

For now I fixed the default alignement, and I set all money to be aligned right, and have also monospace (looks cool when having amounts with different lengths)

**Comment by mauthi** [comment]
From my perspective I’m not sure if setting the alignment is needed in FE - I never used the possiblity to change it before (in your system or in any other).
But maybe you can give me an usecase where the client needs to change it?

**Comment by aocneanu** [comment]
>I never used the possiblity to change it before (in your system or in any other).

My neither, centered is always perfect for me. And I don't even use column visiblity.

>But maybe you can give me an usecase where the client needs to change it?

I can't give you any use case when either the dev or the user **needs** to change it.

But having this control in the FE would allow everyone to configure their tables however she or he **wants**, or see fit.

**Comment by mauthi** [comment]
> But having this control in the FE would allow everyone to configure their tables however she or he wants, or see fit.
I agree that would be the best solution (if setting a default value by the dev is possible). 

But I think this is not so easy (not the programming but the position of control) - therefore I would see it as a good solution that as 1st step the dev can set the default alignment in config and as 2nd step the user is able to change it in frontend.

**Comment by justinmoh** [comment]
@mauthi I agree with you _preference_, which at many occurrences we simply need to decide the best for our users, for example, `crtNo` would be ideally _centered_, but `name` probably best left aligned, and probably action buttons are right aligned... purely personal preference, maybe.

Anyway in my situation it makes `alignment control` kind of totally useless, and since it's useless, I cannot show that to my users -- it's chaos when they click it. Then I realise `Enso` also doesn't provide default setting API for this.

I think I will contribute some customisations and decoupling improvement in later time. But for now I'll have to modify the component directly for good.

**Comment by aocneanu** [comment]
Done :)
