### ISSUE TITLE
Money values not rendered correctly

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/VueDatatable#46]
This is  a bug.

### Description
I have the column defined as the following:
```
{
            "label": "Amount",
            "name": "amount",
            "data": "amount",
            "money": {
                "symbol": "€",
                "format": "%s %v",
                "precision": 2,
                "thousand": ".",
                "decimal": ","
            },
            "meta": [ "searchable", "sortable", "total" ]
        },
```
Value in database: 150.00
Output: € 15.000,00
![screenshot 2018-03-30 10 57 20](https://user-images.githubusercontent.com/7204559/38131932-3c3604e4-3409-11e8-8a89-840f38ac8ed6.png)

### Steps to Reproduce
see above

### Expected behavior
Output: € 150,00

### Actual behavior
Output: € 15.000,00

**Comment by aocneanu** [comment]
You provided waaay to little info.

copy paste from your code in the table template

![image](https://user-images.githubusercontent.com/16073274/38134597-6a1f636a-341c-11e8-98de-885e94585e51.png)

db

![image](https://user-images.githubusercontent.com/16073274/38134605-74a77c50-341c-11e8-9838-704ea1d08d25.png)

output

![image](https://user-images.githubusercontent.com/16073274/38134641-a0f90698-341c-11e8-88c0-f96992266b64.png)

**Comment by aocneanu** [comment]
I managed to replicate.

**Comment by mauthi** [comment]
do you need more information?

**Comment by aocneanu** [comment]
Nope, I'm on it
