### ISSUE TITLE
Localisation of ExportNotification

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/VueDatatable#47]
This is  a bug.

### Description
There are some localisation things missing:
- Notification text (`'Export emailed: '.$this->name.' Table'`)
- Subject of mail
- BroadcastMessage? (`export notification`)
- Mail Text is OK

### Steps to Reproduce
Start a report
Start `php artisan queue:work`

### Expected behavior
Text should be translateable

### Actual behavior
Text is in english only

**Comment by aocneanu** [comment]
Open a PR and add the `__` where is missing. Probably `ExportNotification.php`

**Comment by mauthi** [comment]
closed with #48
