### ISSUE TITLE
Reload other component if delete is finished

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/VueDatatable#49]
This is  a help request.

### Description
I try to do the following:
- After a row is deleted an other component should be reloaded

My problem is:
- neither the destroy nor the ajax event on table is send after the deletion has finished
- Would it be possible to add an after deletion finished event?

**Comment by aocneanu** [comment]
>neither the destroy nor the ajax event on table is send after the deletion has finished

How are you listening for the event? paste the code pls.

**Comment by mauthi** [comment]
Table:
```
<vue-table class="box"
	    	:path="path"
	        id="partneraccountentries"
	        :filters="filters"
	        :params="params"
	        @destroy="destroy"
	        @ajax="ajax"
	        @ajax-finished="ajaxFinished">
	    </vue-table>
```

Methods:
```
ajax() {
            	console.log("ajax");
            },
            destroy(row) {
            	console.log("destroy");
            },
            ajaxFinished() {
            	console.log("ajax-finished");

            	this.reloadOverview();
            }
```

In VueTable.vue I added the following line:
```
ajax(method, path) {
            axios[method.toLowerCase()](path).then(({ data }) => {
                this.$toastr.success(data.message);
                this.getData();
                this.$emit('ajax-finished'); // ADDED
            }).catch(error => this.handleError(error));
        },
```

Output if I am destroying row:
```
destroy
ajax
ajax-finished
```

Conclusion:
- destroy: called before row is deleted
- ajax: called before row is deleted
- ajax-finished: called after row is deleted > This is what I would need. If OK, can we add this call to VueTable.vue?

**Comment by aocneanu** [comment]
Sorry, you initial email was clear, I didn't paid attention.

I added:

- `postEvent` as optional attribute in the button's config. When using combined with the `ajax` type it will emit the specified event if the ajax was successful. 

- `draw` event is emitted at every table draw, after the ajax from `getData`

**Comment by aocneanu** [comment]
@gandesc please update the docs

**Comment by mauthi** [comment]
Thx - perfect!
