### ISSUE TITLE
After reload table shows hidden columns

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/VueDatatable#5]
1st load of table - column "url" is hidden and can be shown with "+" button:
<img width="986" alt="screenshot 2017-12-10 14 54 53" src="https://user-images.githubusercontent.com/7204559/33805491-25e50eec-ddba-11e7-94b8-80296e887ebc.png">

After reload of the table - column "url" is displayed as normal column:
<img width="1009" alt="screenshot 2017-12-10 14 51 58" src="https://user-images.githubusercontent.com/7204559/33805494-2cceb442-ddba-11e7-9268-b533a7653bc0.png">

**Comment by aocneanu** [comment]
Hi,

This is hard for me to reproduce. Maybe if you can put something up I can look at it. The responsive directive tries to resize the table every time the table's wrapping container changes.

From what I understand with the last column visible the table exists the viewport right?

Also, I just fixed the other problem, with the extra column when not having actions, so maybe we will not encounter this behaviour.

Please test and post again.

Cheers.

**Comment by mauthi** [comment]
will do...

**Comment by mauthi** [comment]
Not possible to reproduce it after fix #4 (https://github.com/laravel-enso/VueDatatable/commit/6aaa44b090faf46c7320e5142496e8cfda3f4136)
