### ISSUE TITLE
Customize modal message

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/VueDatatable#53]
This is  a feature request.

### Description
I would like to do the following:
- I have an invoice table
- At the end I have a button: Send Invoice to client
- In the modal I would like to show something like: The selected invoice will be send to client (<client_email). Are you sure?
- I have the client email as rogue column in table 
- But I don't know how to get it into modal text??

Is this possible somehow?

**Comment by aocneanu** [comment]
how are you showing the modal?

**Comment by mauthi** [comment]
found a solution, sorry, my mistake
