### ISSUE TITLE
global button does not appear 

### ISSUE THREAD

**Issue by shonhor22** [laravel-enso/VueDatatable#57]
This is  a **bug request**.

### Steps to Reproduce

my barilgaTable.json

```
"buttons": [
    "excel",
    "create",
    "edit",
    "destroy",
    {
      "type": "global",
      "icon": "trash",
      "class": "is-danger",
      "routeSuffix": "delete",
      "event": "delete",
      "postEvent": "delete-done",
      "action": "ajax",
      "method": "PATCH",
      "label": "Устгах"
    }
  ],

class BarilgaDeleteAction extends Action
{
    public function process()
    {
        \Log::info($this->data());
    }
}

class BarilgaTableController extends Controller
{
    use Datatable, Excel, Action;

    protected $tableClass = BarilgaTable::class;
    protected $actionClass = BarilgaDeleteAction::class;
    protected $chunk = 2;

}

Route::patch('delete', 'BarilgaTableController@action')
                    ->name('delete');

composer updated
```

### Expected behavior

log filtered id
### Actual behavior

button does not appear

**Comment by aocneanu** [comment]
Are you using the table in Enso or outside?

**Comment by shonhor22** [comment]
in enso project

**Comment by aocneanu** [comment]
did you add the permission in the permissions menu? The user's role that you are testing has access to this permission?

**Comment by shonhor22** [comment]
I forgot create permission. Now button appear. But bellow error throw.

2018-04-17 15:54:59] local.ERROR: Trying to get property of non-object {"userId":2,"email":"shonhor22@gmail.com","exception":"[object] (ErrorException(code: 0): Trying to get property of non-object at /Users/shonkhor/Documents/workspace/enso/vendor/laravel-enso/vuedatatable/src/app/Classes/Table/Filters.php:89)

**Comment by aocneanu** [comment]
You have already a ticket open for this.

**Comment by shonhor22** [comment]
I couldn't opened previous  issue so created one
