### ISSUE TITLE
Menu have multiple levels 

### ISSUE THREAD

**Issue by wesssup** [laravel-enso/VueDatatable#58]
This is  a **feature request**.

### Prerequisites
* [ x] Are you running the latest version?
* [ x] Are you reporting to the correct repository?
* [ x] Did you check the documentation?
* [ x] Did you perform a cursory search?

### Description

We are loving this framework but we have some major headache as our business has a requirement that need to implement 2+ levels inside the menu. We already worked on this for 4d+ and are unable to get it right.

How can we do this, is there an update planned? How to write this code ourselves?

If we cannot get this right we cannot use this framework anymore :( 

### Steps to Reproduce
Always

### Expected behavior
Allow the model to have n+ levels, always add a few spaces on the indentation 

### Actual behavior
only 2 levels

**Comment by aocneanu** [comment]
Hi,

I glad you like it, you can show this by staring it :D

I'm not exactly sure what you mean about the menu levels. From a technical point of view, the menu can have virtually any number of levels. The only limitation can be the width of the sidebar in correlation with the menu names.

This took me 45 seconds to achieve, from the interface, `System\Menus` menu, by just setting the parent menu accordingly:

![image](https://user-images.githubusercontent.com/16073274/38920759-b27a06ee-42fc-11e8-96c0-0bf4878fcadc.png)

**Comment by wesssup** [comment]
Hi Adrian,

Sorry my bad, we are using this one  https://github.com/vue-bulma/vue-admin

Kr

Wesley

**Comment by aocneanu** [comment]
Ah :)
