### ISSUE TITLE
Load additional data for one row

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/VueDatatable#6]
Use case:
I have an invoice table - works fine
But I would like to have a possibility to display da items on this invoice after clicking e.g. an info button

Do you have thought on such an use case already?

**Comment by aocneanu** [comment]
If I understand correctly you can take two approaches here. You can either build a designated view for the invoice details, and load this page like the edit form is loaded or build a new component that you will display in the same view (when clicking this button), probably below the table.

For the first approach you also have two flavours :)

- Use the show button, designed specifically for situations like this. In `config/datatable.php` you can check the button configurations and you will see the definition for show:

```
'buttons' = [
   ....
    'row' => [
            'show' => [
                'icon'        => 'fa fa-eye',
                'class'       => 'is-success',
                'routeSuffix' => 'show',
                'event'       => 'show',
                'action'      => 'router',
            ],
            ....
     ],
]
```

`row` means that the button will display on every row.

`routeSuffix` will be what will be appended to the template's `routePrefix` attribute. If you have `invoices` as a `routePrefix` what you'll get is `invoices.show`. You need to have this named permission in your resource controller and take care of the BE logic and FE `show` view.

Now you just need to add the `show` button to the template.

Note: The table will also emit a `show` event when the user clicks the button.

- Define in your template a custom button (object), with a custom route like you see in the readme file.

```
"buttons": [
        .......
        {
            "type": "row",
            "icon": "fa fa-usd",
            "class": "has-text-purple",
            "event": "show-invoice",
            "routeSuffix": "custom", // one
            "fullRoute": "optional.full.route", // or the other
            "action": "router",
        }
    ],
```

You can read all the details about the button options in the readme.

And the second approach would be using an simpler custom button like

```
"buttons": [
        .....
        {
            "type": "row",
            "icon": "fa fa-usd",
            "class": "has-text-purple",
            "event": "show-invoice",
        }
    ],
```

and when you declare the `vue-table` just

```
<vue-table id="invoices"
     .....
     @show-invoice="showInvoice">
</vue-table>
```

then create a method in your vue instance

```
methods() {
    showInvoice(row) {
         axios.get('invoices/' + row.id)...
    }
}
```

where `row` is the object corresponding to the line you click.

Does this cover your use case?

**Comment by mauthi** [comment]
thx, will give that a try and if necessary open issue again
