### ISSUE TITLE
global button confirmation doesn't working

### ISSUE THREAD

**Issue by shonhor22** [laravel-enso/VueDatatable#60]
This is  a **bug request**.

### Steps to Reproduce

"buttons": [
    "excel",
    "create",
    "edit",
    "destroy",
    {
      "type": "global",
      "icon": "trash",
      "class": "is-danger",
      "routeSuffix": "delete",
      "event": "delete",
      "postEvent": "delete-done",
      "action": "ajax",
      "method": "PATCH",
      "label": "Устгах",
      "confirmation": true,
      "message": "Бүх өгөгдлийг устгахдаа итгэлтэй байна уу?"

    }
### Expected behavior

modal open and ask
### Actual behavior

modal doesn't open and action done directly

**Comment by aocneanu** [comment]
This is not a bug, but I will add this enhancement in the following days.
