### ISSUE TITLE
Show all column with bottom scroll

### ISSUE THREAD

**Issue by shonhor22** [laravel-enso/VueDatatable#63]
This is  a ** feature request**.

### Description

datatable has many column's and customer want to show all column and compare rows.
Is there any config to disable hide colums's to additional row.

### Expected behavior

show all column's and scroll appear
### Actual behavior

additional collumn hidden

**Comment by aocneanu** [comment]
Are you thinking of a horizontal scroll for tables that exceed the display width?

**Comment by shonhor22** [comment]
yes table with horizontal scroll

**Comment by ijunaid8989** [comment]
Yes, Can we have this feature?

**Comment by aocneanu** [comment]
Soon :)
