### ISSUE TITLE
Custom Global Buttons on DataTable that do not include "event" property fail

### ISSUE THREAD

**Issue by stotes** [laravel-enso/VueDatatable#64]
https://github.com/laravel-enso/VueDatatable/blob/bcf5c26dd2c111a1ff4a8c59732de563bda7bb03/src/resources/assets/js/components/enso/vuedatatable/TopControls.vue#L156

This is  a **bug**.

### Description
Custom Global Buttons on DataTable that do not include "event" property when defining the button will fail as event is undefined.

//Solution Line 156 TopControls.vue
`if(button.event){
                this.$emit(button.event);
            }   `

**Comment by aocneanu** [comment]
Please use the issue template for the future.
