### ISSUE TITLE
HTTP 414 "Request URI too long" with GET on ExportData of Table with many columns

### ISSUE THREAD

**Issue by stotes** [laravel-enso/VueDatatable#65]
https://github.com/laravel-enso/VueDatatable/blob/bcf5c26dd2c111a1ff4a8c59732de563bda7bb03/src/resources/assets/js/components/enso/vuedatatable/VueTable.vue#L387

I have some very lengthy tables that don't play nice with their long URI's.  My solution has been to change to a POST to overcome the URI issue.

**Comment by aocneanu** [comment]
Please use the issue template for the future
