### ISSUE TITLE
Date Interval Filters

### ISSUE THREAD

**Issue by stevefrost** [laravel-enso/VueDatatable#67]
This is  a **bug **.

### Prerequisites
* [x ] Are you running the latest version?
* [x ] Are you reporting to the correct repository?
* [x ] Did you check the documentation?
* [x ] Did you perform a cursory search?

### Description
Date Interval filters do not appear to be working, it looks to be down to the hasFilters() method inside app/Classes/Table/Builder.php. The frontend passes 'intervals' but it's looking for 'intervalFilters'

### Steps to Reproduce
Add a date interval filter to page, try to filter table

### Expected behavior
Table should filter

### Actual behavior
Table doesn't filter

**Comment by aocneanu** [comment]
Yeah, good catch.
