### ISSUE TITLE
Multiple use of a single table

### ISSUE THREAD

**Issue by stevefrost** [laravel-enso/VueDatatable#69]
I am using the same VueDatatable on two different pages, but I don't want to show certain columns on one of those pages, Can I do that?

**Comment by aocneanu** [comment]
The best way I can think of is having two templates with the desired configuration, and then in your `ModelTable` builder class change the `$templatePath` property value to fit you need.

**Comment by stevefrost** [comment]
How would I pass a param from Vue to the table class init() method?
