### ISSUE TITLE
Edit Button Doesn't work

### ISSUE THREAD

**Issue by naishu** [laravel-enso/VueDatatable#74]
I am trying to implement the Enso Vue Data Table. The data table successfully populates and the sorting, pagination, and search features work. However, the Create, Edit, Delete, and Excel  buttons do not work.

On the page that successfully fetches the data table, I am using the css/enso.css and js/tableExample.js from the Laravel Enso repository.  Do I need to package the frontend dependencies instead with npm?

 

My goal is to get those features to work with the minimum number of Composer Enso packages.  I have installed laravel-enso/vuedatatable, laravel-enso/vuecomponents  and laravel-enso/formbuilder.  Are there other packages that I need to install?

On the datatable.php config file, I changed the method of the Edit button to href from router and it is getting the json data from the controller. How does the Edit form consume the json data? Currently just the json data is displayed and the Edit form doesn't load in the Vue Data Table.

 

I think this is a great project and has very nice features. The complexity coupled with a need for additional documentation and examples makes it a challenge to implement. I tried researching this problem to see if others had posted a solution, but I haven’t had any luck finding answers.  I appreciate any assistance in resolving these issues so I can move forward. I would be happy to post the solution in other online forums so that others who are similarly stuck can benefit.

 

Thanks,
Naishu

**Comment by aocneanu** [comment]
Are you using the components in a SPA? Do you have the vue router available?

The form builder and the table builder are completely separate packages. If you had success getting the table to work, I would suggest trying to build a page where you play only with the form builder. After you figure the form out you will move forward to the table integration.

Leave this open and share here your progress with the formbuilder, and we'll go from there.

**Comment by aocneanu** [comment]
No, you don't need the router. Help me help you by sharing code, errors etc.

**Comment by naishu** [comment]
My goal is to get the data table to work for the Laravel users table with all of its features (edit, create, Excel, etc). I want to get this to work first with the minimum number of Laravel packages and frontend npm dependencies. After I understand it, I can use the same concept for other tables.

 I also really like your package as a good data table solution. Although it is complicated, it looks to be a nice fit for any application that needs to do CRUD.

What steps do I need to follow to get just the data table to work on the users table? I think if you help with this answer, then more people may benefit from following these steps and easily deploy it.

**Comment by aocneanu** [comment]
The package allows a variety of technics and gives you liberty in choosing your implementation.

For instance, as you probably noticed in the example table, each button emits an event according to the configuration of the json template. You can use the event to do whatever you need. If you don't know how to work with events, go to the [vue docs](https://vuejs.org/v2/guide/events.html#ad)

The edit button:

```json
{
      "type": "row",
      "icon": "pencil-alt",
      "class": "is-warning",
      "event": "edit"
},
```

![image](https://user-images.githubusercontent.com/16073274/43503354-a6251cea-9567-11e8-916f-7946e4c9aa8d.png)

If you want to navigate to a page related to a model's that you display in the table you can use the `href` property for a button. Beware that you must also use named routes in your laravel app, as the documentation specifies.

Extracted from `datatables.php`

```json
'download' => [
      'icon' => 'cloud-download-alt',
      'class' => 'is-primary',
      'routeSuffix' => 'download',
      'event' => 'download',
      'action' => 'href',
],
```

The routeSuffix in conjunction with the template's `"routePrefix"` property will represent the named route for this action. The id of the model will be the `dtRowId` attribute that the table needs.

If you don't know about named routes, go to the [laravel docs](https://laravel.com/docs/5.6/routing#named-routes)

Of course, you could use the Vue Router, [docs here](https://router.vuejs.org/)

**Comment by naishu** [comment]
Currently, the buttons are already configured with events and we are using named routes as you described. But when you click the edit, delete, create, and excel buttons, this error shows:

 

Uncaught TypeError: Cannot read property 'push' of undefined

 

In order to display an Enso Vue datatable of the Laravel users table like you have on the picture you shared with the edit, delete, create, excel working what are the minimum composer laravel and npm packages that I need to install, what should the webpack.mix.js look like and what .js file (enso.js, tableExample.js) should be included in the page that calls the vue-table?

**Comment by aocneanu** [comment]
Please share here your `datatables.php` content (only if you made changes to it) and your `table.json` template.

**Comment by naishu** [comment]
Please find the datatables.php and users.json attached.

Currently the Datatable is fetching the data from users table.

[file.zip](https://github.com/laravel-enso/VueDatatable/files/2259994/file.zip)

**Comment by aocneanu** [comment]
@naishu 

I meant paste the code here. I will do it for you.

>In the Method for the edit button, I have changed from router to href.

your `datatable.php` buttons section
```php
'buttons' => [
        'global' => [
            'create' => [
                'icon' => 'plus',
                'class' => 'is-success',
                'routeSuffix' => 'create',
                'event' => 'create',
                'action' => 'router',
                'label' => 'Create',
            ],
            'excel' => [
                'icon' => 'file-excel',
                'class' => null,
                'routeSuffix' => 'exportExcel',
                'event' => 'export-excel',
                'action' => 'export',
                'label' => 'Excel',
            ],
            'action' => [
                'icon' => 'check',
                'class' => null,
                'routeSuffix' => 'action',
                'event' => 'custom-action',
                'postEvent' => 'custom-action-done',
                'action' => 'ajax',
                'method' => 'PATCH',
                'label' => 'Action',
                'message' => 'Custom Action. Are you sure?',
                'confirmation' => true,
            ],
        ],
        'row' => [
            'show' => [
                'icon' => 'eye',
                'class' => 'is-success',
                'routeSuffix' => 'show',
                'event' => 'show',
                'action' => 'router',
            ],
            'edit' => [
                'icon' => 'pencil-alt',
                'class' => 'is-warning',
                'routeSuffix' => 'edit',
                'event' => 'edit',
                'action' => 'router', // guess what...
            ],
            'destroy' => [
                'icon' => 'trash-alt',
                'class' => 'is-danger',
                'routeSuffix' => 'destroy',
                'event' => 'destroy',
                'action' => 'ajax',
                'method' => 'DELETE',
                'message' => 'The selected record is about to be deleted. Are you sure?',
                'confirmation' => true,
                'postEvent' => 'destroyed',
            ],
            'download' => [
                'icon' => 'cloud-download-alt',
                'class' => 'is-primary',
                'routeSuffix' => 'download',
                'event' => 'download',
                'action' => 'href',
            ],
        ],
    ],
```

your users.json template
```json
"buttons": ["excel", "create", "show", "edit", "destroy"],
```
