### ISSUE TITLE
When Table have 0 results, it's showing me empty table instead "No records were found"

### ISSUE THREAD

**Issue by b-stavitskiy** [laravel-enso/VueDatatable#78]
This is  a **bug**.

### Prerequisites
- [x] Are you running the latest version?
- [x] Are you reporting to the correct repository?
- [x] Did you check the documentation?
- [x] Did you perform a cursory search?

### Description
When Table have 0 results, it's showing me empty table instead "No records were found".
**Important!** Table have "join" condition and dynamic filter for the table that joins (not main table).

I got VueTable, which have join, here is code for my query:
```
public function query()
{
    return (new Client)->select(\DB::raw(
        'clients.id as "dtRowId", clients.client_first_name, clients.client_lastname, clients.client_surname'
    ))->join('client_phones', 'clients.id', '=', 'client_phones.client_id');
}
```
I modified "LaravelEnso\VueDatatable\app\Classes\Table\Builder" class to output queries:
```
private function run()
{
    $this->filtered = $this->count = $this->count();

    dump($this->query->toSql());

    $this->setDetailedInfo()
        ->filter()
        ->sort()
        ->setTotal()
        ->limit()
        ->setData()
        ->setAppends()
        ->toArray()
        ->computeEnum()
        ->computeDate();

    dd($this->query->toSql());
}
```
Output:
```
select clients.id as "dtRowId", clients.client_first_name, clients.client_lastname, clients.client_surname from `clients` inner join `client_phones` on `clients`.`id` = `client_phones`.`client_id`
```
```
select clients.id as "dtRowId", clients.client_first_name, clients.client_lastname, clients.client_surname from `clients` inner join `client_phones` on `clients`.`id` = `client_phones`.`client_id` where (`client_phones`.`client_phone` in (?)) limit 10 offset 0
```
So attribute "$this->count" is set before full query exposed. Let's move to front-end file "components/enso/vuedatatable/VueTable.vue":
```
<div v-if="body && !body.count"
    class="has-text-centered no-records-found">
    {{ i18n('No records were found') }}
</div>
```
```
hasContent() {
    return this.body && this.body.count;
},
```
So, "count" ignoring filters, because of that my Table when it have 0 results showing me empty table instead "No records were found".

### Steps to Reproduce
1. Create Table Backend&Frontend that uses join table.
2. Add dynamic frontend filter to VueTable
3. Search impossible condition

### Expected behavior
Table show me "No records were found".

### Actual behavior
Showing me empty table.
![image](https://user-images.githubusercontent.com/39275809/43460985-ea2cfb70-94da-11e8-9176-d16a6c8c476b.png)
(Image is just an example, how results looks like)

**Comment by aocneanu** [comment]
I added a filter on the existing users index.vue, where we have joins

```php
return User::select(\DB::raw(
                'users.id as "dtRowId", owners.name as owner, users.first_name, users.last_name, users.phone,
                users.email, roles.name as role, users.is_active'
            ))->join('owners', 'users.owner_id', '=', 'owners.id')
            ->join('roles', 'users.role_id', '=', 'roles.id');
```

After I added a filter on the joined table (owners)

This is when the value exists:

![image](https://user-images.githubusercontent.com/16073274/43505318-3a524206-956f-11e8-8a28-ce4c66e7b98f.png)

This is when the value is wrong:

![image](https://user-images.githubusercontent.com/16073274/43505402-7f2e5ca2-956f-11e8-9636-df4572ba73d1.png)

I really don't understand where the problem lies.

**Comment by aocneanu** [comment]
Should I close this?

**Comment by b-stavitskiy** [comment]
I will add more details today (UTC+3), sorry that it takes so long.

**Comment by b-stavitskiy** [comment]
closed due lack of time.
