### ISSUE TITLE
Filtering a null value

### ISSUE THREAD

**Issue by stevefrost** [laravel-enso/VueDatatable#80]
This could be a **bug  or a feature request**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
I want to filter a table where a columns value is null

### Steps to Reproduce
set up a filter on a column with a null value

### Expected behavior
Only show rows where the field is null

### Actual behavior

It's showing all fields

My guess is that a null filter is intended to be the default state, but I want to show all rows in a table where the "approved_by" field is null, (ie It hasn't been approved)

**Comment by aocneanu** [comment]
I've been really caught up these days, sorry for the delayed response.

If you want to filter a null column use the `params` property. This property allows doing all kinds of custom logic where the package does not offer automation .

```vue
<vue-table :params="{ table: { column: null } }"
    ....../>
```

In your TableBuilder you have access to a `request()` [helper](https://github.com/laravel-enso/VueDatatable/blob/master/src/app/Classes/Table.php#L20) that returns an [Obj](https://github.com/laravel-enso/Helpers/blob/master/src/app/Classes/Obj.php) (you can check the available methods)

Next you can do something like:

```php
    $params = json_decode($this->request()->get('params'));
```

in your TableBuilder and integrate the param in your query.

**Comment by stevefrost** [comment]
Thanks once again
