### ISSUE TITLE
Installing Vue Data Table Independently

### ISSUE THREAD

**Issue by kmcelwrath** [laravel-enso/VueDatatable#82]
This is a feature request

### Description
Has anyone been successful at installing Vue data table independently of the Enso ecosystem? If so, can you post the steps?  

Do I need to install the Enso core and additional npm modules not in the instructions?

### Steps to Reproduce
I followed the instructions and I can get the table to load but I can't get edit or create to work. 

### Expected behavior
Full functionality for the Edit and Create buttons

### Actual behavior
No errors but I only get the event message and nothing happens.

**Comment by aocneanu** [comment]
Ok:) from now on it’s not a vuedatatable issue. Open a dedicated issue on the formbuilder repo and post there your code related to the edit page so I can help.
