### ISSUE TITLE
Help, the counter does not work in join and leftjoin queries!

### ISSUE THREAD

**Issue by heyner29** [laravel-enso/VueDatatable#86]
This is  a **bug | feature request**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

I have a query that commits several tables, I do it according to the example that exists in users and only gets the first records, it seems that the counter does not work. I would like someone to help me or guide me in what I am doing wrong.

The query is:
```ruby
public function query()
    {
        return Ticket::select(\DB::raw(
            'tickets.id as "dtRowId", tickets.ticketid, tickets.tickettype, receipts.datenew,
            people.name as person, customers.name as customer, SUM(payments.total) as "total", tickets.status, 
            closedcash.host as caja'
          ))->join('receipts', 'tickets.id', '=', 'receipts.id')
            ->join('closedcash', 'receipts.money', '=', 'closedcash.money')
            ->leftJoin('payments', 'receipts.id', '=', 'payments.receipt')
            ->leftJoin('customers', 'customers.id', '=', 'tickets.customer')
            ->leftJoin('people', 'tickets.person', '=', 'people.id')
            ->groupBy('tickets.id', 'tickets.ticketid', 'tickets.tickettype', 'receipts.datenew', 'people.name', 'customers.name')
            ->orderBy('receipts.datenew', 'desc');
    }
```

### Actual behavior
![captura de pantalla de 2018-08-23 12-44-54](https://user-images.githubusercontent.com/12703614/44542635-07902e80-a6d3-11e8-9269-3095e1911e2e.png)
The filter does it without problems but does not count the total number of records yet. In this table are a little more than 10,000
![captura de pantalla de 2018-08-23 12-51-15](https://user-images.githubusercontent.com/12703614/44542789-72da0080-a6d3-11e8-878d-03c3669d3127.png)

Thank you in advance for your help

**Comment by aocneanu** [comment]
The problem lies in using `groupBy`.

If you have the default `sql_mode=only_full_group_by` (which you should..) then at least `tickets.status` in your selection should throw `Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column tickets.status ......`

the same for `closedcash.host as caja`. The latter for instance should return ambiguous values because of the grouping by `receipts.datenew`. You can have different hosts without the group, but after grouping sql would have to choose one resulting in inconsistent data. When using groupBy this way you may get different results just by running the exact same query again.

At the first sight the above query looks like it relies on a database architecture that may be improved.

Now back to the actual technical problem, the package uses the `->count()` method to determine the total records number, before applying any filters, and then one more time with filters. Based on the result it computes the pagination.`count()` does not play well with `groupBy()`

Let's say we have the following query:

```sql
User::select(\DB::raw('users.owner_id'))->join('owners', 'users.owner_id', 'owners.id')->groupBy('users.owner_id')->count()
```

You would expect as a result the exact number of owners. But in fact the generated query is:

```sql
select count(*) as aggregate from `users` inner join `owners` on `users`.`owner_id` = `owners`.`id` group by `users`.`owner_id`
```

instead of

```sql
select count(*) from (select * from `users` inner join `owners` on `users`.`owner_id` = `owners`.`id` group by `users`.`owner_id`)
```

Look on laravel/framework repository after this issue to understand more.

Tip: Use laravel-debugbar in development so you can inspect your queries and better understand what happens under the hood.

P.S: The only time I use `groupBy()` in my queries is *never* :)

**Comment by heyner29** [comment]
Thanks for the quick reply.
In part I was able to solve the problem by correcting the query a little. At the moment it seems to work, I still have a little mess with the `SUM ()`, without this operation and without the `groupBy` everything works.
![captura de pantalla de 2018-08-24 22-28-20](https://user-images.githubusercontent.com/12703614/44614576-271b7a00-a7ed-11e8-9b08-dd1ad8f42355.png)
Do you know any way to replace the `SUM ()` in the query ?. It is to add the total of the invoice.
This is the new query:
```ruby
Ticket::select(\DB::raw(
            'tickets.id as "dtRowId", tickets.ticketid, tickets.tickettype, receipts.datenew,
            people.name as person, customers.name as customer, tickets.status, 
            closedcash.host as host'
        ))->join('receipts', 'tickets.id', '=', 'receipts.id')
            ->join('closedcash', 'receipts.money', '=', 'closedcash.money')
            ->leftJoin('payments', 'receipts.id', '=', 'payments.receipt')
            ->leftJoin('customers', 'customers.id', '=', 'tickets.customer')
            ->leftJoin('people', 'tickets.person', '=', 'people.id')
            ->where('tickets.tickettype', '=', 0);
```

**Comment by aocneanu** [comment]
You can do this in several ways..

One way would be adding an [accessor](https://laravel.com/docs/5.6/eloquent-mutators#defining-an-accessor) to the ticket model that would compute the sums. You have a few [examples](https://github.com/laravel-enso/Enso/blob/master/app/Tables/Templates/users.json#L18) with accessors in Enso's tables. You will have to define the access in the model, select the `models.id` in the `TableBuilder` separately from the `dtRowId`, add the field to the json template and that's it.

The problem with this approach is that the accessor is not searchable nor sortable. You can't use totals either.

Another approach would be something llike

```php
public function query()
{
     return Ticket::select(\DB::raw(
            'tickets.id as "dtRowId", tickets.ticketid, tickets.tickettype, receipts.datenew,
            people.name as person, customers.name as customer, tickets.status, 
            closedcash.host as host, amounts.total'
        ))->join('receipts', 'tickets.id', '=', 'receipts.id')
            ->join('closedcash', 'receipts.money', '=', 'closedcash.money')
            ->leftJoin('payments', 'receipts.id', '=', 'payments.receipt')
            ->leftJoin('customers', 'customers.id', '=', 'tickets.customer')
            ->leftJoin('people', 'tickets.person', '=', 'people.id')
            ->join($this->amounts(), 'tickets.id', '=', 'amounts.ticket_id`)
            ->where('tickets.tickettype', '=', 0);
}
```

Notice the `$this->amounts()` method and the `amounts.total` field in the main select.

Add then to the builder a new method

```php
private function amounts()
{
      return \DB::row('(select sum(payments.value) as total from payments group by payments.ticket_id) as amounts');
}
```

It's more of a pseudocode, I don't know exactly the structure behind but you get the idea.

Now you have sorting, filtering, totals in the datatable and so on.

But again, when you come to doing something like you may have already did something sub optimal in the DB design.

**Comment by heyner29** [comment]
Thank you very much, I will work on the solution taking into account your recommendations.
By the way congratulations, for such an excellent package / template.

**Comment by aocneanu** [comment]
Thank you too.

If you really like stuff from Enso please support it by starring packages that you enjoy using or help you.
