### ISSUE TITLE
handleError, how is it handled? 

### ISSUE THREAD

**Issue by clnt** [laravel-enso/VueDatatable#90]
This is  a **question**.

### Prerequisites
* [✅] Are you running the latest version?
* [✅] Are you reporting to the correct repository?
* [✅] Did you check the documentation?
* [✅] Did you perform a cursory search?

### Description
I am currently adding success/error messages to my api endpoints, however when returning an error code and a message, no error message is displayed with toastr?

What is `this.handleError(error)` and how is it intended to work/be handled?

I am returning an error like this from my controller: `return response()->json(['message' => __('messages.group.delete.error', ['id' => $groupId])], 500);`

Which gives me response data like this:
```
   "response":{
      "data":{
         "message":"Monitor group not found with ID 1"
      },
      "status":500,
      "statusText":"Internal Server Error",
    }
```

### Steps to Reproduce
Create `ajax` delete action on a row button, and return a response from the endpoint: `return response()->json(['message' => __('messages.group.delete.error', ['id' => $groupId])], 500);`

### Expected behavior
I would expect an error Toastr alert to be displayed with the contents of `response.data.message` if it is set.

### Actual behavior
No error alert message is shown

**Comment by aocneanu** [comment]
All Enso packages / pages use the [`handleError()`](https://github.com/laravel-enso/Core/blob/master/src/resources/assets/js/modules/enso/mixins/errorHandler.js) mixin that in conjunction with [`EnsoException`](https://github.com/laravel-enso/Helpers/blob/master/src/app/Exceptions/EnsoException.php) allows displaying the error in a toaster.

You can use `EnsoException` directly, or extend it in a `CustomException` or you can write your own exception but use `555` as the error code.

Let me know if I can help you further.

**Comment by clnt** [comment]
Thanks for the explanation :) Sounds good! 👍 

Not going to have time to look into this today so I will close it and reopen if I have any futher questions :)
