### ISSUE TITLE
Is it possible to use eloquent relationships in the query?

### ISSUE THREAD

**Issue by heyner29** [laravel-enso/VueDatatable#92]
This is  a **Question**.

### Prerequisites
* [X] Are you running the latest version?
* [X] Are you reporting to the correct repository?
* [X] Did you check the documentation?
* [X] Did you perform a cursory search?

### Description
I would like to ask if it is possible to use the relationships of eloquent, every time I try to use them I return null. If possible, I could get advice on how to do it.
Thanks in advance.

**Comment by heyner29** [comment]
Sorry, the problem is mine, it was that I was not putting in the select the foreign key. Sorry to create the issues without exhausting all the possibilities

**Comment by heyner29** [comment]
I'm back here, the response json brings the relationship as the image shows. But if I try to access any of the values in the array, it does not show it.

![captura de pantalla de 2018-09-13 00-48-59](https://user-images.githubusercontent.com/12703614/45469454-3c4e3f00-b6ef-11e8-9caa-6fc8a25ca621.png)

I want to show only the name of the product, I try to do with `product.name` in `data` or `name` column but it does not show anything.

**Comment by aocneanu** [comment]
It is possible now. You'll have to define the path to your attribute in the `name` attribute of the `column` object in the JSON template.

We didn't support this before because such columns cannot be sorted or filtered dynamically, but I guess it's no harm having it as an option.

**Comment by matthewhutchings** [comment]
@heyner29 How did you manage to get Eloqent to return the query builder with the key id?
