### ISSUE TITLE
Skip columns for export

### ISSUE THREAD

**Issue by shusharin** [laravel-enso/VueDatatable#97]
This is  a **feature request**.

### Prerequisites
* [+] Are you running the latest version?
* [+] Are you reporting to the correct repository?
* [+] Did you check the documentation?
* [+] Did you perform a cursory search?

### Description

Hi! Is there any way to skip some columns for excel export?
I didn't find that in documentation.

Example: i have some custom columns rendered by slots. Like this:
`// column item from templateTable.json`
```
, {
            "label": "Tags",
            "name": "tags",
            "data": "tags",            
            "align": "left",
            "meta": [ 
                "slot"                
            ]
 }
```

`// query in CallTable class `
```
public function query()
{        
        return Call::select(\DB::raw('calls.*, calls.id as "dtRowId"))
                ->with('tags')
                ;
}
```

When i try export, i have error "Undefined index: tags"

Maybe we can add flag in meta column "no_export" or something like this?

Example: 
`// column item from templateTable.json`
```
{
            "label": "Tags",
            "name": "tags",
            "data": "tags",            
            "align": "left",
            "meta": [ 
                "slot",
                "no_export"
            ]
 }
```

**Comment by aocneanu** [comment]
`notExportable`
